<p>If this fan motor can generate more power than it consumes, perhaps one
could make a "perpetual motion" machine out of it.  Likely, it uses the
magnets to give it the extra boost, and the magnets would wear out
eventually...  Not right away.</p>

<p>This could make a wonderful generator for a house, portable electronic
device, or for third world countries.  It would look awesome on your desk at
work.</p>

<p>Below is a copy of the text and images from a snapshot taken on
2004-02-12.  Special thanks to the <a href="http://www.archive.org">Way-Back
Machine</a> and <a href="http://www.japan.com">Japan.com</a>.</p>

<p>You can also check out a local copy of the patents he filed with the U.S.
Patent Office:  <a href="fan/5594289.tif">5,594,289</a> and <a
href="fan/4751486.tif">4,751,486</a>.</p>

<?= Separator() ?>

<p><b>The Techno Maestro's  Amazing Machine</b><br>
<b>Kohei Minato and the Japan Magnetic Fan Company</b><br>
<br>
<i>A maverick inventor's breakthrough electric motor uses permanent magnets to make power &nbsp;--&nbsp; and has investors salivating</i>
<br>
by John Dodd</p>

<p align=center>
<img src="fan/minato30.jpg" width="250" height="193" border="0" alt="">

<p>
When WE first got the call from an excited colleague that he'd just seen the most amazing invention&nbsp;--&nbsp;a magnetic motor that consumed almost no electricity&nbsp;--&nbsp;we were so skeptical that we declined an invitation to go see it. If the technology was so good, we thought, how come they didn't have any customers yet?
<br>
<br>
We forgot about the invitation and the company until several months later, when our friend called again.
<br>
<br>
"OK," he said. "They've just sold 40,000 units to a major convenience store chain. Now will you see it?"
<br>
<br>
In Japan, no one pays for 40,000 convenience store cooling fans without being reasonably sure that they are going to work.
<br>
<br>
<b>The maestro</b>
<br>
<br>
The streets of east Shinjuku are littered with the tailings of the many small factories and workshops still located there&nbsp;--&nbsp;hardly one's image of the headquarters of a world-class technology company. But this is where we are first greeted outside Kohei Minato's workshop by Nobue Minato, the wife of the inventor and co-director of the family firm.
<br>
<br>
The workshop itself is like a Hollywood set of an inventor's garage. Electrical machines, wires, measuring instruments and batteries are strewn everywhere. Along the diagram-covered walls are drill presses, racks of spare coils, Perspex plating and other paraphernalia. And seated in the back, head bowed in thought, is the 58-year-old techno maestro himself.
<br>
<br>
Minato is no newcomer to the limelight. In fact, he has been an entertainer for most of his life, making music and producing his daughter's singing career in the US. He posseses an oversized presence, with a booming voice and a long ponytail. In short, you can easily imagine him onstage or in a convertible cruising down the coast of California&nbsp;--&nbsp;not hunched over a mass of wires and coils in Tokyo's cramped backstreets.
<br>
<br>
Joining us are a middle-aged banker and his entourage from Osaka and accounting and finance consultant Yukio Funai. The banker is doing a quick review for an investment, while the rest of us just want to see if Minato's magnetic motors really work. A prototype car air conditioner cooler sitting on a bench looks like it would fit into a Toyota Corolla and quickly catches our attention.

<p align=center>
<img src="fan/minato101.jpg" width="250" height="166" border="0" alt="">

<p>

<b>Seeing is believing</b>
<br>
<br>
Nobue then takes us through the functions and operations of each of the machines, starting off with a simple explanation of the laws of magnetism and repulsion. She demonstrates the "Minato Wheel" by kicking a magnet-lined rotor into action with a magnetic wand.
<br>
<br>
Looking carefully at the rotor, we see that it has over 16 magnets embedded on a slant&nbsp;--&nbsp; apparently to make Minato's machines work, the positioning and angle of the magnets is critical. After she kicks the wheel into life, it keeps spinning, proving at least that the design doesn't suffer from magnetic lockup.
<br>
<br>
She then moves us to the next device, a weighty machine connected to a tiny battery. Apparently the load on the machine is a 35kg rotor, which could easily be used in a washing machine. After she flicks the switch, the huge rotor spins at over 1,500 rpms effortlessly and silently. Meters show the power in and power out. Suddenly, a power source of 16 watt or so is driving a device that should be drawing at least 200 to 300 watts.
<br>
<br>
Nobue explains to us that this and all the other devices only use electrical power for the two electromagnetic stators at either side of each rotor, which are used to kick the rotor past its lockup point then on to the next arc of magnets. Apparently the angle and spacing of the magnets is such that once the rotor is moving, repulsion between the stators and the rotor poles keeps the rotor moving smoothly in a counterclockwise direction. Either way, it's impressive.
<br>
<br>
Next we move to a unit with its motor connected to a generator. What we see is striking. The meters showed an input to the stator electromagnets of approximately 1.8 volts and 150mA input, and from the generator, 9.144 volts and 192mA output. 1.8 x 0.15 x 2 = 540mW input and 9.144 x 0.192 = 1.755W out.
<br>
<br>
But according to the laws of physics, you can't get more out of a device than you put into it. We mention this to Kohei Minato while looking under the workbench to make sure there aren't any hidden wires.
<br>
<br>
Minato assures us that he hasn't transcended the laws of physics. The force supplying the unexplained extra power out is generated by the magnetic strength of the permanent magnets embedded in the rotor. "I'm simply harnessing one of the four fundamental forces of nature," he says.
<br>
<br>
Although we learned in school that magnets were always bipolar and so magnetically induced motion would always end in a locked state of equilibrium, Minato explains that he has fine-tuned the positioning of the magnets and the timing of pulses to the stators to the point where the repulsion between the rotor and the stator (the fixed outer magnetic ring) is transitory. This creates further motion&nbsp;--&nbsp;rather than a lockup. (See the sidebar on page 41 for a full explanation).

<p align=center>
<img src="fan/minato40.jpg" width="250" height="166" border="0" alt="">

<p>
<b>Real products</b>
<br>
<br>
Nobue Minato leads us to the two devices that might convince a potential investor that this is all for real.
<br>
<br>
First, she shows us the cooling fan prototype that is being manufactured for a convenience store chain's 14,000 outlets (3 fans per outlet). The unit looks almost identical to a Mitsubishi-manufactured fan unit next to it, which is the unit currently in wide use. In a test, the airflow from both units is about the same.
<br>
<br>
The other unit is the car air conditioning prototype that caught our eye as we came in. It's a prototype for Nippon Denso, Japan's largest manufacturer of car air conditioners. The unit is remarkably compact and has the same contours and size as a conventional unit. Minato's manufacturing skills are clearly improving.

<p align=center>
<img src="fan/minato45.jpg" width="250" height="166" border="0" alt="">

<p>
<b>The banker and his investment</b>
<br>
<br>
Minato has good reason to complain about Japan's social and cultural uniformity. For years, people thought of him as an oddball for playing the piano for a living, and bankers and investors have avoided him because of his habit of claiming that he'd discovered a breakthrough technology all by himself&nbsp;--&nbsp;without any formal training.
<br>
<br>
However, the Osaka banker stands up after the lecture and announces that before he goes, he will commit \100 million to the investment pool.
<br>
<br>
Minato turns to us and smiles. We brought him good luck, and this was his third investor in as many weeks to confirm an interest.
<br>
<br>
<b>Bringing the tech to the table</b>
<br>
<br>
With the audience gone, we ask Minato what he plans to do to commercialize the technology. His game plan is simple and clear, he says. He wants to retain control, and he wants to commercialize the technology in Japan first&nbsp;--&nbsp;where he feels he can ensure that things get done right. Why doesn't he go directly to the US or China? His experiences in both countries, he suggests, have been less than successful. "The first stage is critical in terms of creating good products and refining the technology. I don't want to be busy with legal challenges and IP theft while doing that."
<br>
<br>
Still, the export and licensing of the technology are on his agenda, and Minato is talking to a variety of potential partners in other countries.
<br>
<br>
Whereas another inventor might be tempted to outsource everything to a larger corporation, part of what drives Minato is his vision of social justice and responsibility. The 40,000 motors for the convenience store chain are being produced by a group of small manufacturers in Ohta-ku and Bunkyo-ku, in the inner north of Tokyo&nbsp;--&nbsp;which is becoming a regional rust belt. Minato is seized with the vision of reinvigorating these small workshops that until the 80s were the bedrock of Japan's manufacturing and economic miracle. Their level of expertise will ensure that the quality of the motors will be as good as those from any major company.

<p align=center>>
<img src="fan/minato65.jpg" width="250" height="166" border="0" alt="">

<p>
<b>International prep</b>
<br>
<br>
Despite his plan to do things domestically first, Minato is well prepared for the international markets. He is armed with both six years of living and doing business in Los Angeles in the early 90s&nbsp;--&nbsp;and with patent protection for over 48 countries. His is hardly a provincial perspective.
<br>
<br>
His US experience came after playing the piano for a living for 15 years. He began tinkering with his invention in the mid-70s. The idea for his magnetic motor design came from a burst of inspiration while playing the piano.
<br>
<br>
But Minato decided to drop everything in 1990 to help his daughter Hiroko, who at the age of 20 decided that she wanted to be a rhythm and blues star in the US. Minato is a strong believer in family: If Hiroko was going to find fame and fortune in the US, Dad had better be there to help manage her. He suceeded in helping Hiroko to achieve a UK dance chart number one hit in 1995.
<br>
<br>
In 1996 Minato returned to Japan and his magnetic motor project. The following year he displayed his prototypes to national power companies, government officials and others at a five-day conference in Mexico City. Interest was palpable, and Minato realized that his invention might meet a global need for energy-saving devices.
<br>
<br>
Subsequent previews and speeches in Korea and Singapore further consolidated his commitment to bringing the invention to fruition, and he was able to bring in several early-stage investors.
<br>
<br>
During the late 90s, Minato continued to refine his prototypes. He also stayed in constant contact with his lawyer, registering patents in major countries around the world. Through his experiences in the US he realized that legal protection was critical, even if it meant delaying release of the technology by a couple of years.
<br>
<br>
Ironically, by the time he'd won patents in 47 countries, the Japanese patent office turned him down on the grounds that "[the invention] couldn' t possibly work" and that somehow he was fabricating the claims.
<br>
<br>
But a few months later they were forced to recant their decision after the US patent office recognized his invention and gave him the first of two patents. As Minato notes: "How typical of Japan's small-minded bureaucrats that they needed the leadership of the US to accept that my invention was genuine."
<br>
<br>
By 2001, the Minatos had refined their motors and met enough potential investors to enter into a major international relationship, initially with a Saudi company, to be followed thereafter by companies in the US and elsewhere.
<br>
<br>
However, fate dealt the investors and Minato's business a serious blow when the World Trade Center was attacked in New York. The Saudis retreated, and Minato's plans fell back to square one.
<br>
<br>
Now Minato is once again ready to move. With the first order in the works and more orders pending successful prototypes, he has decided that investors don't have to be primary partners. He is actively accepting inquiries from corporate investors who can bring strategic advantages and corporate credibility with them. His company, Japan Magnetic Fan, will make a series of investment tie-up announcements in the first and second quarters of 2004.

<p align=center>
<img src="fan/minato98.jpg" width="250" height="166" border="0" alt="">

<p>
<b>Implications</b>
<br>
<br>
Minato's motors consume just 20 percent or less of the power of conventional motors with the same torque and horse power. They run cool to the touch and produce almost no acoustic or electrical noise. They are significantly safer and cheaper (in terms of power consumed), and they are sounder environmentally.
<br>
<br>
The implications are enormous. In the US alone, almost 55 percent of the nation's electricity is consumed by electric motors. While most factory operators buy the cheapest motors possible, they are steadily being educated by bodies like NEMA (National Electrical Manufacturers Association) that the costs of running a motor over a typical 20-year lifespan comprise a purchase price of just 3 percent of the total, and electricity costs of 97 percent. It is not unusual for a $2,000 motor to consume $80,000 of electricity (at a price of .06 cents per kilowatt hour).
<br>
<br>
Since 1992, when efficiency legislation was put into place at the US federal level, motor efficiency has been a high priority&nbsp;--&nbsp;and motors saving 20 percent or so on electrical bills are considered highly efficient. Minato is about to introduce a motor which saves 80 percent, putting it into an entirely new class: The $80,000 running cost will drop to just $16,000. This is a significant savings when multiplied by the millions of motors used throughout the USA and Japan&nbsp;--&nbsp;and eventually, throughout the world.

<p align=center>
<img src="fan/minato76.jpg" width="250" height="166" border="0" alt="">

<p>
<b>The devices</b>
<br>
<br>
Minato's invention and its ability to use remarkably less power and run without heat or noise make it perfect for home appliances, personal computers, cellphones (a miniature generator is in the works) and other consumer products.
<br>
<br>
The magnetic motor will be cheaper than a standard motor to make, as the rotor and stator assemblies can be set into plastic housings, due to the fact that the system creates very little heat. Further, with the motor's energy efficiency, it will be well suited for any application where a motor has limited energy to drive it. While development is still focused on replacing existing devices, Minato says that his motor has sufficient torque to power a vehicle.
<br>
<br>
With the help of magnetic propulsion, it is feasible to attach a generator to the motor and produce more electric power than was put into the device. Minato says that average efficiency on his motors is about 330 percent.
<br>
<br>
Mention of Over Unity devices in many scientific circles will draw icy skepticism. But if you can accept the idea that Minato's device is able to create motion and torque through its unique, sustainable permanent magnet propulsion system, then it makes sense that he is able to get more out of the unit than he puts in in terms of elctrical power. Indeed, if the device can produce a surplus of power for longer periods, every household in the land will want one.
<br>
<br>
"I am not in this for the money," Minato says. "I have done well in my musical career, but I want to make a contribution to society&nbsp;--&nbsp;helping the backstreet manufacturers here in Japan and elsewhere. I want to reverse the trends caused by major multinationals. There is a place for corporations. But as the oil industry has taught us, energy is one area where a breakthrough invention like this cannot be trusted to large companies."
<br>
<br>
Minato was once close to making a deal with Enron. But today, he is firmly on a mission to support the small and the independent&nbsp;--&nbsp;and to go worldwide with them and his amazing machine. "Our plan is to rally smaller companies and pool their talent, and to one day produce the technology across a wide range of fields."
<br>
<br>
Content provided by <a href="http://www.japaninc.com" target="_blank">J@pan Inc. Magazine</a>.