<p>To kill weeds, you should wait until fall.  Then spray a weak solution of
children's shampoo on the lawn.  This washes the grime off the yard allowing
your grass to make better use of sunlight while also making the weeds more
susceptable to weed killers.  Use 1 tablespoon shampoo per gallon water.
Feel free to mix it with your weed killer so you have a 2-in-1 solution.
Spray just the weeds, not the whole yard because weed killer retards plant
growth.</p>

<?php MakeBoxTop('center', 'width: 60%') ?>

<p><b>Spot Treatment Recipe</b>

<p>1 qt water<br>
1 oz children's shampoo<br>
1 oz vinegar<br>
&frac12; oz gin

<p>Put sprayer on stream and just nail the weeds.  The mixture will clean
and stick to weeds and dry them out.

<?php MakeBoxBottom() ?>

<p>To feed your lawn, use four pounds Epsom salts (makes the lawn green) and
one pound confectioner's sugar (gives plants energy).  Plants need sugar and
starch.  Typically, they produce their own via photosynthesis, however you
will be providing the materials without the lawn doing any work.  Use a
rotary spreader set to half your fertilizer's recommended settings.  Spread
before noon in both the fall and spring.  It makes a huge plume of dust, so
you might seriously consider a mask if you don't normally use one when
spreading fertilizer.</p>

<p>When watering your lawn, the below mixture.  Spray it on your lawn every
three weeks.  Also, spray it directly over your fall and spring fertilizer
session.  Warning: Your lawn will get slippery.</p>

<?php MakeBoxTop('center', 'width: 60%') ?>

<p><b>Watering Mixture</b>

<p>&frac12; c warm water<br>
&frac12; molasses (more sugars = more energy)
1 can beer (composts thatch faster)<br>
1 c children's shampoo (wash away dust)
1 c household ammonia (nitrogen)

<p>Mix molasses and water first, then add beer.  Move to be over your lawn
and add the soap; it can make lots of bubbles.  Top off the mixture with
ammonia.</p>

<?php MakeBoxBottom() ?>

<p>When mowing, use a sharp blade.  The goal is to cut the lawn, not rip the
lawn.  Mow later in the evening so the lawn can heal at night and will avoid
the tops of the blades of grass from turning brown.  Sharpen your mower
blades often.  Mow regularly and do not trim more than 1/3 the length of the
blades of grass at a time.  If you were negligent, mow once, wait a couple
days, and then mow again.</p>

<p>If you can step on your lawn and the grass doesn't bounce back up, it
needs watering.  Water in the mornings for 45 minutes.  If you have used the
shampoo mixture, the water will seep right into the soil for the plants to
use.  The deeper the water goes, the better the plant roots.</p>

<p>Aerate your lawn.  Rent an aerating machine annually.  This will let
nutrients get to your lawn easier.</p>

<p>If you have an insect problem, you can manage it with this mixture.  It
kills disease, makes insects sick, and poisons them.</p>

<?php MakeBoxTop('center', 'width: 60%') ?>
		       
<p><b>Pest Control Tonic</b>

<p>1/3 hunk fatty lye soap<br>
4 oz flea and tick shampoo<br>
large pinch of chewing tobacco<br>
1 quart antiseptic mouthwash

<p>Dissolve the lye soap into a quart of boiling water.  Add the shampoo.

<p>Boil the chewing tobacco in another quart of water.  Filter out the
leaves to leave a tobacco tea.

<p>Mix equal parts of the shampoo-lye solution, tobacco tea, and mouthwash.
Spray on your lawn with a setting of one tablespoon per gallon.

<?php MakeBoxBottom() ?>
