<?php
/* Sprint File Uploader
 * 
 * Copyright (C) 2003-2005 - Tyler Akins
 * Licensed under the GNU GPL software license.
 * See the LEGAL file for legal information
 * See http://rumkin.com/tools/sprint/ for more information about these tools
 */

?>

<p>Sure!  Head on over to the <a href="../downloads.php">Download Page</a> and
you can download the source code to the uploader.  You can take it apart and
see how I handle the  <?php echo FAQLink('cache', 'caching issues') ?>,
<?php echo FAQLink('gcd', 'GCD File') ?> generation, image resizing, and other
tricks.</p>
