<?php
/* Sprint File Uploader
 * 
 * Copyright (C) 2005 - Tyler Akins
 * Licensed under the GNU GPL software license.
 * See the LEGAL file for legal information
 * See http://rumkin.com/tools/sprint/ for more information about these tools
 */

?>

<p>If the file you sent to your phone gets placed in the wrong folder, that
could be the cause of several problems:</p>

<ul>
<li>If you are uploading a midlet (.jar file), make sure you are specifying
the correct folder if you don't want the default.
<li>If you are uploading a .mp4 file and it is not ending up in your
"Ringers" folder, try renaming it to .m4a.
<li>You can sometimes use BitPim and a data cable to move files around your
phone.
</ul>
