<?php
/* Sprint File Uploader
 * 
 * Copyright (C) 2003-2005 - Tyler Akins
 * Licensed under the GNU GPL software license.
 * See the LEGAL file for legal information
 * See http://rumkin.com/tools/sprint/ for more information about these tools
 */

?>

<p>The short answer is that your phone can not handle that type of file.
I suggest trying a different type.  If you tried an MP3, maybe a MIDI would
work better.</p>

<p>The long answer is that your phone's browser is able to be extended with
plugins and one was not yet loaded to handle that media type.  As far as
I know, there are no plugins available for loading by users to any phone.</p>

<p>The ending result is that you're stuck and your phone does not and will
not support that type of file.</p>