<p>The uploader will resize your images to fit on your phone.  This has
numerous benefits:

<ul>
<li>You don't need to worry about whether the image will be too large for
your phone
<li>You don't need to resize the image by yourself
<li>You don't actually need to know the screen size of your phone
<li>The image will be resized, preserving the aspect ratio so that you don't
get a stretched or squished picture
<li>Your phone will use less memory displaying and storing the picture,
leaving more free for other ringers and pictures
</ul>

<p>Images that are smaller than your screen size are not enlarged.  If you
need them to fill your screen, enlarge them before you upload them.</p>