<?php

$GLOBALS['Tests']['Candy'] = array(
	'Version' => '1.0',
	'Summary' => 'How does your selection of a candy bar reflect your ' . 'views on life?',
	'Data' => array(
		array(
			'Question' => 'If you were buying candy and you had your choice of the 
	     candy bars listed below, which would you choose?',
			'Answers' => array(
				'Baby Ruth' => 'Sweet, loving, cuddly.  You love all warm fuzzy items.  A
		  little nutty.  Sometimes you need an ice cream cone at the
		  end of the day.',
				'3 Musketeers' => 'You are adventurous, love new ideas, are a champion of 
		  underdogs and a slayer of dragons.  When tempers flare up,
		  you whip out your sabre.',
				'Butterfinger' => 'Smooth, sexy, and articulate with your hands.  You are
		  an excellent after-dinner speaker and a good teacher.
		  But don\'t try to walk and chew gum at the same time.',
				'Snickers' => 'Fun-loving, sassy, humorous.  Everyone enjoys being around
		  you, but you are a practical joker.  Others should be
		  cautious in shaking hands.  However, you are a friend for
		  life.',
				'Hershey\'s' => 'Romantic, warm, loving.  You care about other people and
		  can be counted on in a pinch.  You tend to melt.',
				'Almond Joy' => 'Sexy, always ready to give and receive, very energetic,
		  and really likes to get into life.  The opposite sex is
		  always attracted to you.',
				'Clark Bar' => 'You like sports, whether football, baseball, basketball,
		  or soccer.  If you could, you would like to participate,
		  but you still enjoy watching sports.  You don\'t like to
		  give up the remote control.',
				'Good \'n\' Plenty' => 'You are a very fun-loving person who likes to laugh.
		  You are fun to be with.  People like to hang out with you.
		  You are a very warm-hearted person.',
				'Energy Bar' => 'Life is passing you by.  Get a life!  Go eat a plum.',
				'Chocolate Coated Rasins' => 'You go to the bathroom often.'
			)
		)
	)
);
