<?PHP

// This list is placed in the public domain
// It was copied in by Tyler Akins, but the true source is listed below

// Just comment out the providers that you do not wish to support.
// List is from http://www.sensiblesoftware.com/Cell-Phone-Email-List.asp
// with many additions from people visiting the phone uploader site
// http://rumkin.com/tools/sprint/

$GLOBALS['Providers'] = array(
'@rumkin.com',                   // Rumkin - for testing only

'@sms.3rivers.net',	         // 3 River Wireless
'@paging.acswireless.com',	 // ACS Wireless
'@sms.net.nz',                   // Advanced Global Communications
'@advantagepaging.com',		 // Advantage Communications
'@myairmail.com',		 // Airtouch Pagers
'@alphapage.airtouch.com',	 // Airtouch Pagers
'@airtouch.net',		 // Airtouch Pagers
'@airtouchpaging.com',		 // Airtouch Pagers
'@alphanow.net',		 // AlphNow
'@txt.aliant.net',		 // Aliant
'@alltelmessage.com',		 // Alltel
'@message.alltel.com',		 // Alltel PCS
'@paging.acswireless.com',	 // Ameritech Paging
'@pageapi.com',			 // Ameritech Paging
'@clearpath.acswireless.com',	 // Ameritech Clearpath
'@airtelap.com',		 // Andhra Pradesh Airtel
'@archwireless.net',		 // Arch Pagers (PageNet)
'@epage.arch.com',		 // Arch Pagers (PageNet)
'@archwireless.net',		 // Arch Pagers (PageNet)
'@mobile.att.net',		 // AT&T PCS
'@txt.att.net',                  // AT&T PCS
'@dpcs.mobile.att.net',		 // AT&T Pocketnet PCS
'@mmode.com',                    // AT&T M-Mode (Formerly Cingular)
'@beepwear.net',		 // Beepwear
'@sms.beemail.ru',		 // BeeLine GSM
'@message.bam.com',		 // Bell Atlantic
'@text.bell.ca',		 // Bell Canada
'@txt.bellmobility.ca',		 // Bell Canada
'@txt.bell.ca',                  // Bell Canada
'@bellmobility.ca',		 // Bell Canada
'@txt.bellmobility.ca',		 // Bell Mobility
'@bellsouthtips.com',		 // Bell South (Blackberry)
'@sms.bellsouth.com',		 // Bell South
'@wireless.bellsouth.com',	 // Bell South
'@blsdcs.net',			 // Bell South
'@bellsouth.cl',		 // Bell South
'@blsdcs.net',			 // Bell South Mobility
'@sms.bluecell.com',		 // Bluegrass Cellular
'@myboostmobile.com',            // Boost Mobile
'@bplmobile.com',		 // BPL mobile
'@cmcpaging.com',		 // Carolina Mobile Communications
'@sms.celcom.com.my',		 // Celcom
'@phone.cellone.net',		 // Cellular One East Coast
'@swmsg.com',			 // Cellular One South West
'@paging.cellone-sf.com',	 // Cellular One PCS
'@mobile.celloneusa.com',	 // Cellular One
'@cellularone.txtmsg.com',	 // Cellular One
'@cellularone.textmsg.com',	 // Cellular One
'@cell1.textmsg.com',		 // Cellular One
'@message.cellone-sf.com',	 // Cellular One
'@sbcemail.com',		 // Cellular One
'@pix.cellularsouth.com',	 // Cellular South
'@csouth1.com',			 // Cellular South
'@gophoto.onthe-go.net',	 // Centennial
'@cw.com',			 // Centennial Wireless
'@myblue.com',			 // Centennial Wireless
'@cvcpaging.com',		 // Central Vermont Communications
'@messaging.centurytel.net',	 // CenturyTel
'@rpgmail.net',			 // Chennai RPG Cellular
'@airtelchennai.com',		 // Chennai Skycell / Airtel
'@mobile.att.net',		 // Cincinnati Bell
'@gocbw.com',			 // Cincinnati Bell Wireless
'@cingular.com',		 // Cingular Wireless
'@cingularme.com',		 // Cingular Wireless
'@mms.mycingular.com',		 // Cingular Wireless
'@mobile.mycingular.com',	 // Cingular Wireless
'@mobile.mycingular.net',	 // Cingular Wireless
'@mycingular.textmsg.com',	 // Cingular Wireless
'@msg.clearnet.com',		 // Clearnet
'@comcastpcs.textmsg.com',	 // Comcast
'@pageme.comspeco.net',		 // Communication Specialists
'@pager.comspeco.com',		 // Communication Specialist Companies
'@sms.comviq.se',		 // Comviq
'@cookmail.com',		 // Cook Paging
'@corrwireless.net',		 // Corr Wireless Communications
'@mms.mycricket.com',		 // Cricket
'@airtelmail.com',		 // Delhi Aritel
'@delhi.hutch.co.in',		 // Delhi Hutch
'@page.hit.net',		 // Digi-Page / Page Kansas
'@mobile.dobson.net',		 // Dobson Cellular Systems
'@mobile.cellularone.com',	 // Dobson-Alex Wireless / Dobson-Cellular One
'@t-mobile-sms.de',		 // DT T-Mobile
'@sms.edgewireless.com',	 // Edge Wireless
'@sms.emt.ee',			 // EMT
'@escotelmobile.com',		 // Escotel
'@fido.ca',			 // Fido
'@webpager.us',			 // GCS Paging
'@bplmobile.com',		 // Goa BPLMobil
'@sms.goldentele.com',		 // Golden Telecom
'@epage.porta-phone.com',	 // GrayLink / Porta-Phone
'@airmessage.net',		 // GTE
'@gte.pagegate.net',		 // GTE
'@messagealert.com',		 // GTE
'@celforce.com',		 // Gujarat Celforce
'@text.houstoncellular.net',	 // Houston Cellular
'@ideacellular.net',		 // Idea Cellular
'@page.infopagesystems.com',	 // Infopage Systems
'@inlandlink.com',		 // Inland Cellular Telephone
'@pager.tdspager.com',		 // The Indiana Paging Co
'@jsmtel.com',			 // JSM Tele-Page
'@escotelmobile.com',		 // Kerala Escotel
'@airtelkol.com',		 // Kolkata Airtel
'@smsmail.lmt.lv',		 // Kyivstar
'@e-page.net',			 // Lauttamus Communication
'@smsmail.lmt.lv',		 // LMT
'@bplmobile.com',		 // Maharashtra BPL Mobile
'@ideacellular.net',		 // Maharashtra Idea Cellular
'@text.mtsmobility.ca',		 // Manitoba Telecom Systems
'@text.mtsmobility.com',	 // Manitoba Telecom Systems
'@mci.com',			 // MCI Phone
'@pagemci.com',			 // MCI
'@mymeteor.ie',			 // Meteor
'@page.metrocall.com',		 // Metrocall
'@my2way.com',			 // Metrocall 2-way
'@mymetropcs.com',		 // Metro PCS
'@metorpcs.sms.us',		 // Metro PCS
'@fido.ca',			 // Microcell
'@clearlydigital.com',		 // Midwest Wireless
'@m1.com.sg',			 // MiWorld
'@page.mobilcom.net',		 // Mobilecom PA
'@mobilecomm.net',		 // Mobilecomm
'@m1.com.sg',			 // Mobileone
'@page.mobilfone.com',		 // Mobilfone
'@ml.bm',			 // Mobility Bermuda
'@mobistar.be',			 // Mobistar Belgium
'@sms.co.tz',			 // Mobitel Tanzania
'@mobtel.co.yu',		 // Mobtel Srbija
'@beepone.net',			 // Morris Wireless
'@isp.com',			 // Motient
'@correo.movistar.net',		 // Movistar
'@text.mts.net',		 // MTS Canada
'@bplmobile.com',		 // Mumbai BPL Mobile
'@orangemail.co.in',		 // Mumbai Orange
'@wirefree.informe.ca',		 // NBTel
'@sms.netcom.no',		 // Netcom
'@messaging.nextel.com',	 // Nextel
'@page.nextel.com',		 // Nextel
'@nextel.com.br',		 // Nextel
'@npiwireless.com',		 // NPI Wireless
'@pcs.ntelos.com',		 // Ntelos
'@omnipoint.com',		 // Omnipoint
'@omnipointpcs.com',		 // Omnipoint
'@onemail.at',			 // One Connect Austria
'@onlinebeep.net',		 // OnlineBeep
'@optusmobile.com.au',		 // Optus Mobile
'@orange.net',			 // Orange
'@orangemail.co.in',		 // Orange Mumbai
'@sms.orange.nl',		 // Orange - NL / Dutchtone
'@mujoskar.cz',			 // Oskar
'@sms.luxgsm.lu',		 // P&T Luxembourg
'@pacbellpcs.net',		 // Pacific Bell
'@pagemart.net',		 // PageMart
'@airmessage.net',		 // PageMart Advanced /2way
'@pmcl.net',			 // PageMart Canada
'@pagegate.pagenet.ca',		 // PageNet Canada
'@page1nw.com',			 // PageOne NorthWest
'@pcsone.net',			 // PCS One
'@msg.pioneerenidcellular.com',	 // Pioneer / Enid Cellular
'@text.plusgsm.pl',		 // PlusGSM
'@bplmobile.com',		 // Pondicherry BPL Mobile
'@voicestream.net',		 // Powertel
'@mobilecell1se.com',		 // Price Communications
'@primeco.textmsg.com',		 // Primco
'@sms.primtel.ru',		 // Primtel
'@page.propage.net',		 // ProPage
'@sms.pscel.com',		 // Public Service Cellular
'@qwestmp.com',			 // Qwest
'@qwest.sprintpcs.com',		 // Qwest (Partnered with Sprint)
'@ram-page.com',		 // RAM Page
'@pcs.rogers.com',		 // Rogers AT&T Wireless
'@pcs.rogers.com',		 // Rogers Canada
'@info2go.com',			 // Rural Cellular Corp
'@safaricomsms.com',		 // Safaricom
'@sms.sasktel.com',		 // Sasktel Mobility
'@sms.sasktel.net',		 // Sasktel Mobility
'@pcs.sasktelmobility.com',	 // Sasktel Mobility
'@satelindogsm.com',		 // Satelindo GSM
'@satellink.net',		 // Satellink
'@paging.acswireless.com',	 // SBC Ameritech Paging
'@scs-900.ru',			 // SCS-900
'@sfr.fr',			 // SFR France
'@skytel.com',			 // Skytel Pagers
'@email.skytel.com',		 // Skytel Pagers
'@text.simplefreedom.net',	 // Simple Freedom
'@mysmart.mymobile.ph',		 // Smart Telecom
'@page.southernlinc.com',	 // Southern LINC
'@email.swbw.com',		 // Southwestern Bell
'@sprintpaging.com',		 // Sprint
'@sprintpcs.com',		 // Sprint PCS
'@messaging.sprintpcs.com',	 // Sprint PCS
'@page.stpaging.com',		 // ST Paging
'@tms.suncom.com',		 // SunCom
'@suncom1.com',			 // SunCom
'@mysunrise.ch',		 // Sunrise Mobile
'@freesurf.ch',			 // Sunrise Mobile
'@mobile.surewest.com',		 // Surewest Communications
'@bluewin.ch',			 // Swisscom
'@tmomail.net',			 // T-Mobile
'@tmail.com',                    // T-Mobile
'@t-mobile.com',		 // T-Mobile
'@tbayteltxt.net',               // TBay Tel
'@tmomail.com',			 // T-Mobile
'@voicestream.net',		 // T-Mobile
'@sms.t-mobile.at',		 // T-Mobile
'@t-d1-sms.de',			 // T-Mobile
'@t-mobile.uk.net',		 // T-Mobile UK
'@bplmobile.com',		 // Tamil Nadu BPL Mobile
'@sms.tele2.lv',		 // Tele2 Latvia
'@teleflip.com',		 // Teleflip
'@movistar.net',		 // Telefonica Movistar
'@mobilpost.no',		 // Telenor
'@pageme.teletouch.com',	 // Teletouch
'@gsm1800.telia.dk',		 // Telia Denmark
'@msg.telus.com',		 // Telus
'@mms.telusmobility.com',	 // Telus
'@telus.net',			 // Telus Services (CA)
'@timnet.com',			 // TIM
'@tms.suncom.com',		 // Triton
'@alphame.com',			 // TSR Wireless
'@beep.com',			 // TSR Wireless
'@utext.com',			 // Unicel
'@sms.uraltel.ru',		 // Uraltel
'@email.uscc.net',		 // US Cellular
'@mms.uscc.net',		 // US Cellular
'@uscellular.net',		 // US Cellular
'@uscc.textmsg.com',		 // US Cellular
'@uswestdatamail.com',		 // US West
'@escotelmobile.com',		 // Uttar Pradesh Escotel
'@myairmail.com',		 // Verizon Pagers
'@vtext.com',			 // Verizon PCS
'@myvzw.com',			 // Verizon PCS
'@vzw.com',			 // Verizon Wireless
'@vzwpix.com',			 // Verizon Wireless
'@pager.irkutsk.ru',		 // Vessotel
'@vmobl.ca',                     // Virgin Mobile Canada
'@vmobl.com',			 // Virgin Mobile
'@vmobile.ca',			 // Virgin Mobile Canada
'@vmobile.com',			 // Virgin Mobile
'@vmpix.com',			 // Virgin Mobile
'@virgin.ca',			 // Virgin Mobile Canada
'@sms.vodafone.it',		 // Vodafone Italy
'@c.vodafone.ne.jp',		 // Vodafone Japan
'@h.vodafone.ne.jp',		 // Vodafone Japan
'@t.vodafone.ne.jp',		 // Vodafone Japan
'@vodafone.es',			 // Vodafone Spain
'@vodafone.net',		 // Vodafone UK
'@voicestream.net',		 // VoiceStream / T-Mobile
'@airmessage.net',		 // WebLink Wiereless
'@pagemart.net',		 // WebLink Wiereless
'@sms.wcc.net',			 // West Central Wireless
'@cellularonewest.com',		 // Western Wireless
'@wyndtell.com',		 // Wyndtell
);