<?php
/* Sprint File Uploader
 * 
 * Copyright (C) 2003-2005 - Tyler Akins
 * Licensed under the GNU GPL software license.
 * See the LEGAL file for legal information
 * See http://rumkin.com/tools/sprint/ for more information about these tools
 */

?>

<p>So far, lots of phones do not work with GIF files at all.  Also, some
phones that do display GIF files do not work when it is an animated GIF.
Lastly, if the image is resized to fit your phone, the resizer only can
handle the first frame of your GIF file.  You'll need to find a way to
resize your animated GIF to fit the size of your phone.</p>
