<?php
/* Sprint File Uploader
 * 
 * Copyright (C) 2003-2007 - Tyler Akins
 * Licensed under the GNU GPL software license.
 * See the LEGAL file for legal information
 * See http://rumkin.com/tools/sprint/ for more information about these tools
 */

?>

<p>This site does not charge you anything.  The only way I get any money
from anyone is if they decide to donate.  This is not to say that your
provider will not charge!</p>

<p>The uploader requires internet access.  If your plan does not have
unlimited internet access, you may get charged.  This would fall into the
"web browsing" type of category.  Check your plan to see if you get
charged.</p>

<p>If you decided to fill in the "Send To" field so that an SMS message
is sent to your phone, you may get SMS-related charges.  Again, check your
plan to see if you have unlimited text messages or not.</p>

<p>In short, I do not charge for anything but your provider may charge a
bundle.</p>
