<?php
/* Sprint File Uploader
 * 
 * Copyright (C) 2003-2005 - Tyler Akins
 * Licensed under the GNU GPL software license.
 * See the LEGAL file for legal information
 * See http://rumkin.com/tools/sprint/ for more information about these tools
 */

?>

<p>I only use your email address or phone number to send you a message.
It doesn't get logged anywhere, except possibly in my mail log.  I do
not collect, store, sell, or give your private information to anyone.</p>

<p>The information you give me may go into my mail server's log (email is used for sending most SMS messages).  I will not share any information off of my server without a warrant or other means of legally forcing me to hand it over.</p>

<p>Also, like all web servers, I record your request and IP address.  Again, I don't do anything with them.</p>

<p>Files that are uploaded are stored in a database and are expired after a few days.</p>

<p>If you feel that this site is still a security risk, you can email me or just use <a href="../links.php#uploaders">another tool</a>.</p>
