<p>Getting my webcam to see in the dark is a very interesting idea.  What if
you modified a webcam to <a
href="http://homepage.ntlworld.com/geoff.johnson2/IR/">see IR</a>, but you
did not insert the two black filters.  That way, you theoretically would see
in IR if it is dark and not in IR if it is bright enough for color.  The
perfect solution.</p>

<p>Looking at money in IR is an interesting technique, but you could also
look at flowers and other things in nature.  Supposedly, flowers have very
neat IR and UV patterns.</p>