<?PHP
/* Sprint File Uploader
 *
 * Copyright (C) 2003-2005 - Tyler Akins
 * Licensed under the GNU GPL software license.
 * See the LEGAL file for legal information
 * See http://rumkin.com/tools/sprint/ for more information about these tools
 */
?>

<p>The Sprint Uploader will let you send various files to your phone.  Want
a prettier background or a funky new ringer?  That is what this tool is
for.</p>

<p>I should write more, but I really don't know what else to say that isn't
said better elsewhere in the <a href="index.php">FAQ</a>.</p>