<?PHP
/* Sprint File Uploader
 *
 * Copyright (C) 2003-2005 - Tyler Akins
 * Licensed under the GNU GPL software license.
 * See the LEGAL file for legal information
 * See http://rumkin.com/tools/sprint/ for more information about these tools
 */
?>

<p>This is because you are not downloading the file directly from Sprint.
You should normally just press Continue and download the file.</p>

<p>I've been told that you need to make a deal with Sprint, pay $400 for a
VeriSign certificate, and add some special tags to sign the .gcd and .jad
files that I spit out.  Sorry, I don't make enough to shell out that kind of
money for .jad files and then figure out whatever I need to do for .gcd
files.</p>
