<p>First off, the BlueStealth software sold by e-stealth.com is a <a href="http://www.mobile-spy.com/e-stealth.html">scam</a>.  Demand your money back or call your credit card company and contest the charges, saying that the sofware "does not work as advertised".</p>

<p>If you still want to get this on your phone, you can check out the <a href="../tutorials.php">video tutorials</a> page for instructions on how to load this software on your phone.</p>
