<p>Sorry if I redirected you to this FAQ entry after you emailed me.  I get several questions about BlueStealth and decided to write up a page with a thorough explanation instead of one-line responses going back and forth for a while.  Hopefully you understand why and appreciate the level of detail on this page.</p>

<p>First off, the BlueStealth software sold by e-stealth.com is a scam (<a href="http://www.mobile-spy.com/e-stealth.html">more info here</a>).  Everyone who has ever talked to me about it has had issues getting it on their phone or had problems getting a refund.  Demand your money back or call your credit card company and contest the charges, saying that the sofware is defective and does not work as advertised.</p>

<p>Secondly, I am not affiliated with these people.  They send you over to this site because the uploader works for most people.  It's an easy way to get the problems (you) out of their hair.  Please do not email me when the software does not work or if it just won't install no matter how hard you try.  Email the people who own the site where you purchased the software.</p>

<p>Now, if you are reading this, there is still a large chance you still want to get this on your phone.  You can check out the <a href="../tutorials.php">video tutorials</a> page for instructions on how to load this software on your phone, or follow the basic procedure below.</p>

<ol>
<li>Go to the <a href="../index.php">upload page</a> with your computer.
<li>Browse for the file you want to upload
	<ul>
	<li>It is called bloover.jar, if I recall correctly.
	<li>You want to select the .jar file, not the .jad file.
	</ul>
<li>Enter a description of "BlueStealth"
<li>Leave the "Send To" field blank.
<li>Upload the file.
<li>Once uploaded, write down the jump code presented.
<li><b>Switch to your phone</b>
<li>On your phone, open up the web browser.
<li>Enter in the following URL.  <tt>http://rumkin.com/tools/sprint/jump.php</tt>
	<ul>
	<li>Sorry, I don't know how your particular web browser does it, but it is probably in a menu somewhere.
	</ul>
<li>Your phone should show a screen where you can enter a jump code.  Enter the one you wrote down earlier.
<li>Press the button to get the file.
<li>If asked about installing untested/untrusted software, you say Ok/Yes to install it.  If you have doubts and you got this far, you can cancel the download.
<li>Good luck using it.
</ol>

<p>Special notes:</p>

<ul>
<li>No, .jar files do not drectly install on Palm OS phones.  They need to be .prc files.  I am aware that there was a really horrible converter, but it didn't do system-specific stuff, like talk to your Bluetooth transmitter.  You need to get a Palm OS version or a refund.
<li>No, .jar files do not install on a Windows Mobile device.  You might have received another file and you should sync it with your cable.
<li>If you have issues downloading it and wish to try a cable, I have links to some software on the <a href="../links.php">Links</a> page.
<li>If you get a system error or some other message, check out my <a href="/tools/decision_tree/index.php?Tree=uploader">Problems Troubleshooter</a>.
</ul>
