<?PHP
/* Sprint File Uploader
 *
 * Copyright (C) 2003-2005 - Tyler Akins
 * Licensed under the GNU GPL software license.
 * See the LEGAL file for legal information
 * See http://rumkin.com/tools/sprint/ for more information about these tools
 */
?>

<p>The file was too big for your phone.  Try making the audio shorter or
lower quality.  Try shrinking the video.  Try freeing up space on your
phone.  However, most likely, you didn't chop your ringer down to 30 seconds
and downgrade it to mono at a low bitrate.</p>
