<?PHP
/* Sprint File Uploader
 *
 * Copyright (C) 2003-2005 - Tyler Akins
 * Licensed under the GNU GPL software license.
 * See the LEGAL file for legal information
 * See http://rumkin.com/tools/sprint/ for more information about these tools
 */
?>

<p>The error means that your <?PHP echo FAQLink('gcd', 'GCD') ?> file is not 100% 
perfect.  Look for answers in the <?PHP echo FAQLink('e905', 'Data Error 905') 
?> FAQ topic and in the <?PHP echo FAQLink('gcd', 'GCD') ?> section.</p>

<p>If you are using this uploader, you should never see error 906.</p>
