<?PHP
/* Sprint File Uploader
 *
 * Copyright (C) 2003-2005 - Tyler Akins
 * Licensed under the GNU GPL software license.
 * See the LEGAL file for legal information
 * See http://rumkin.com/tools/sprint/ for more information about these tools
 */
?>

<p>The uploader will accept a ton of different formats, but that does not
mean that your phone supports downloading and displaying them.  Another FAQ
topic deals with what <?PHP echo FAQLink('phones', 'phones support') ?>.</p>

<ul>
<li><b>Images:</b> <a href="../formats.php#jpg">jpg</a>, 
<a href="../formats.php#jpg">jpeg</a>, <a href="../formats.php#png">png</a>, 
<a href="../formats.php#wbmp">wbmp</a>, <a href="../formats.php#pmd">pmd</a>,
<a href="../formats.php#cmx">cmx</a></li>
<li><b>Sounds:</b> <a href="../formats.php#mid">mid</a>, 
<a href="../formats.php#mid">midi</a>, <a href="../formats.php#qcp">qcp</a>,
<a href="../formats.php#mp3">mp3</a>, <a href="../formats.php#mmf">mmf</a></li>
<li><b>Midlets:</b> <a href="../formats.php#jar">jar</a>, 
<a href="../formats.php#jad">jad</a></li>
</ul>
	
<p>For a detailed description of the different file types, check out
the <a href="../formats.php">File Formats</a> page.</p>
