<?PHP
/* Sprint File Uploader
 *
 * Copyright (C) 2003-2005 - Tyler Akins
 * Licensed under the GNU GPL software license.
 * See the LEGAL file for legal information
 * See http://rumkin.com/tools/sprint/ for more information about these tools
 */
?>

<p>Midlets are Java programs that are designed to run on very limited
devices, such as your cell phone.  They can be anything from games to web
browsers, calculators to organizers.  There are numerous possible reasons that
a particular midlet will not work on your phone.  Here are just the ones
that I have encountered:</p>

<ul>
<li>The version of Java on your phone isn't recent enough to run the software.
<li>The amount of free heap memory on your phone isn't large enough to run
the program.
<li>It is written to work on a larger screen size than what your phone has.
<li>The midlet is corrupt or the META-INF/MANIFEST.mf file is
missing/malformed.
<li>The file was really a Java applet that was advertised mistakenly as a
midlet.
</ul>

<p>Of all the midlets I have tried, I was very dissapointed.  If I uploaded
10 midlets, only approximately 3 would work.  The trick is to keep at it and
continue trying.  Eventually, you will find a game that works on your phone
and have lots of fun playing it.</p>