<?PHP
/* Sprint File Uploader
 *
 * Copyright (C) 2003-2005 - Tyler Akins
 * Licensed under the GNU GPL software license.
 * See the LEGAL file for legal information
 * See http://rumkin.com/tools/sprint/ for more information about these tools
 */
?>

<p>If you only get <b>X</b> free SMS messages and you want to avoid getting
notifications, you can just leave the "Send To" field blank and no message
will be sent.  You can still download the file with the
<?PHP echo FAQLink('jumpcode', 'jump code') ?> that is shown after the file is
uploaded.  If you were to use your phone and bookmark the page where you
enter the <?PHP echo FAQLink('jumpcode', 'jump code') ?>,
that would be the fastest way to download files from this site.</p>
