<?php
/* Sprint File Uploader
 * 
 * Copyright (C) 2003-2005 - Tyler Akins
 * Licensed under the GNU GPL software license.
 * See the LEGAL file for legal information
 * See http://rumkin.com/tools/sprint/ for more information about these tools
 */

?>

<p>By pointing your phone's web browser to 
<a href="http://rumkin.com/jump">http://rumkin.com/jump</a> you are able to type in the number of
a file to download.  It can be quicker than waiting for an SMS message to
be sent out to you.</p>
