<?PHP
/* Sprint File Uploader
 *
 * Copyright (C) 2003-2005 - Tyler Akins
 * Licensed under the GNU GPL software license.
 * See the LEGAL file for legal information
 * See http://rumkin.com/tools/sprint/ for more information about these tools
 */
?>

<p>To make a <?PHP echo FAQLink('qcp', 'QCP file') ?> louder, you need to increase
the volume of the WAV file before you convert it.</p>

<p>To make a <?PHP echo FAQLink('mp3', 'MP3 file') ?> louder, you need to decode
the MP3 to a WAV file and increase the volume of the WAV file.  Then convert
it back to <?PHP echo FAQLink('mp3', 'MP3') ?>.</p>

<p>To make a MIDI file louder, you will need a program such as 
<a href="http://www.anvilstudio.com/">Anvil Studio</a> to edit the MIDI and
make the individual tracks louder.</p>

<p>Someone even reported that Adobe Audition has built-in filters to
decrease bass and increase vocals and make the song louder overall.  It is
said to work great.</p>
