<?php
/* Sprint File Uploader
 * 
 * Copyright (C) 2003-2005 - Tyler Akins
 * Licensed under the GNU GPL software license.
 * See the LEGAL file for legal information
 * See http://rumkin.com/tools/sprint/ for more information about these tools
 */

?>

<p>First off, you can not create MIDI files from WAV, MP3, AU, or any other
type of file.  MIDI files are similar to sheet music.  It says when to play
a specific note from a specific instrument at a specific time.  The other
types of audio files say what sound to hear at a given time.</p>

<p>If you want to edit MIDI files, try out <a
href="http://www.anvilstudio.com/">AnvilStudio</a>.  It's freeware that will
let you edit MIDI files.</p>

<p>If you just want to find them, go to <a
href="http://google.com">Google</a> and search for MIDI.  Or, check out the
<a href="../links.php">Links Page</a> in the ringer section.</p>
