<?PHP
/* Sprint File Uploader
 *
 * Copyright (C) 2005 - Tyler Akins
 * Licensed under the GNU GPL software license.
 * See the LEGAL file for legal information
 * See http://rumkin.com/tools/sprint/ for more information about these tools
 */
?>

<p>If you are unable to find the ringer, wallpaper, game, or other type of
uploaded file on your phone, you can often find them in a "Downloads"
section.  If that doesn't work, and you usually find the files there, then
the file might have had problems or could have been corrupted.  Your phone
may have rejected the upload.  Usually, if you restart the phone, it will
clear up memory problems.  Take out the battery, wait a few seconds, and put
it back in.  You won't see the file, but at least you could get the memory
back.</p>
