<?PHP
/* Sprint File Uploader
 *
 * Copyright (C) 2003-2005 - Tyler Akins
 * Licensed under the GNU GPL software license.
 * See the LEGAL file for legal information
 * See http://rumkin.com/tools/sprint/ for more information about these tools
 */
?>

<p>Sprint's server tried to access a file that has spaces in it.  Remove the
spaces from the file that gets sent to the phone and this problem should be
fixed.  The uploader here automatically replaces spaces and odd characters
with "_" so you don't need to worry.</p>
