<?php
/* Sprint File Uploader
 * 
 * Copyright (C) 2003-2005 - Tyler Akins
 * Licensed under the GNU GPL software license.
 * See the LEGAL file for legal information
 * See http://rumkin.com/tools/sprint/ for more information about these tools
 */

?>

<p>Yes, it works with almost all phone providers.  The best way to see if it
works with your particular phone and carrier is to just try it.  There is no
registration fee or anything.  As long as your phone has internet access,
you can try this uploader.</p>

<p>Internet access might use up minutes or incur additional charges; see
the details of your particular plan for further information.</p>
