<?PHP
/* Sprint File Uploader
 *
 * Copyright (C) 2003-2005 - Tyler Akins
 * Licensed under the GNU GPL software license.
 * See the LEGAL file for legal information
 * See http://rumkin.com/tools/sprint/ for more information about these tools
 */
?>

<p>There are so many things that cause problems.  Unfortunately, I can not
test them all.  The most common problems that are reported are listed in
this FAQ.  If you get an error message that isn't covered elsewhere or if
you experience problems and can't find a cure in this FAQ, please
email me and let me know about it; my email address is at the bottom
of this page.  Be sure to include the type of phone that you are using and
what the problem is.  Be as detailed as possible.  The more information that
you include, the more likely I can fix the problem.  Include the file you wish
to upload if you can.</p>

<p>Common problems:</p>

<ul>

<li>If you get a specific "Data Error XXX" code, check the FAQ <a
href="index.php">Topic List</a> and see if it is covered.

<li>Your phone does not understand the type of file that you are sending it.
Make sure that you are sending png/gif/jpg images or midi sounds.  Some
phones don't support png, others don't support other things.  Each phone's
capabilities are different.

<li>Animated .gif files are usually not accepted by the phone.  You will need
to change it into an animation (.pmd file) or maybe just use the first frame
of the .gif.

<li>Make sure your file name isn't really long.  Try to make it under 25
characters.  Ideally, it would only be 10-15 letters long.  Spaces and weird
characters are converted automatically to "_" with this uploader.

</ul>
