<?php
/* Sprint File Uploader
 * 
 * Copyright (C) 2003-2005 - Tyler Akins
 * Licensed under the GNU GPL software license.
 * See the LEGAL file for legal information
 * See http://rumkin.com/tools/sprint/ for more information about these tools
 */

?>

<p>I only use your email address or phone number to send you a message.
It doesn't get logged anywhere, except possibly in my mail log.  I do
not collect, store, sell, or give your private information to anyone.  
A longer message about this is on the <a href="../index.php">main page</a>.</p>
