<?php
/* Sprint File Uploader
 * 
 * Copyright (C) 2003-2005 - Tyler Akins
 * Licensed under the GNU GPL software license.
 * See the LEGAL file for legal information
 * See http://rumkin.com/tools/sprint/ for more information about these tools
 */

?>

<p>For this uploader to work, your phone <i>needs</i> internet access.  You
will not be able to download anything unless your phone can connect to this
web site.</p>

<p>Files (ringers, wallpapers, etc.) are not actually text messaged to your
phone.  The address of the site on the internet is what is sent.  SMS
doesn't have a way to send anything except very short messages.</p>
