<?php
/* Sprint File Uploader
 * 
 * Copyright (C) 2008 - Tyler Akins
 * Licensed under the GNU GPL software license.
 * See the LEGAL file for legal information
 * See http://rumkin.com/tools/sprint/ for more information about these tools
 */

?>

<p>Here's a few common providers and their SMS email addresses.  Make sure you replace ### with your full phone number.  Include the area code, and do not include hyphens, periods, or whatever else.  For instance, if your phone number is 333-444-5555, and you were on AT&amp;T, your SMS email address would be 3334445555@mobile.att.net</p>

<table border=1 cellpadding=0 cellspacing=0>
<tr><th align=right>AT&amp;T</th><td>###@mobile.att.net</td></tr>
<tr><th align=right>Sprint</th><td>###@messaging.sprintpcs.com</td></tr>
<tr><th align=right>T-Mobile</th><td>###@tmomail.com</td></tr>
<tr><th align=right>Verizon</th><td>###@vtext.com</td></tr>
</table>
