<?PHP
/* Sprint File Uploader
 *
 * Copyright (C) 2003-2005 - Tyler Akins
 * Licensed under the GNU GPL software license.
 * See the LEGAL file for legal information
 * See http://rumkin.com/tools/sprint/ for more information about these tools
 */
?>

<p>It appears that a couple phones have problems receiving files with this
uploader.  If you can add or correct information on this list, I would love
to hear from you.  Please do not hesitate to email me so I can try to track
down this problem.</p>

<p>If there are issues reported here, I am assuming that your phone does not
work with <b>any</b> web-based uploader.  If you can send something with
another uploader and you are unable to do that with this uploader, I would
<i>love</i> to hear about it!  Test your phone with <a
href="http://www.pix2fone.com">Pix2Fone</a> and the uploader at <a
href="http://www.t1mmy.net/visionTool.html">T1mmy.net</a>.</p>

<?PHP Section('Samsung A460 with Sprint PCS'); ?>

<p>It is impossible to download content
from outside providers with this phone.  You are only allowed to download
content from Sprint's "ringers and more" service.</p>

<?PHP Section('LG VX6100 / LG VX9800 with Verizon') ?>

<ul>
<li>Able to view pictures and hear ringers, but unable to save them.
</ul>

<?PHP Section('RAZR v3c and Motorola e815 on Bell Mobility Canada') ?>

<p>It appears that Bell is only allowing you to download .jar files (games
and applications).  If you try to get a ringer or wallpaper for your phone,
you will get "The requested page can not be displayed."  Apparently, you
need to buy a USB cable or get a bluetooth adaptor for your computer and
then use some other tools on your computer to send the files to your phone.
