<?PHP

$GLOBALS['Tests']['IQ'] = array(
	'Version' => '1.0',
	'Summary' => 'How smart are you?  Quickly take this quiz, if you dare, and find out!',
	'Data' => array(
		array('Question' => 'Do they have a 4th of July in England?',
			'Answers' => array(
				'I Don\'t Know' => 'Incorrect:  Yes, it comes after the ' .
					'third of July.',
				'Yes' => 'Correct.',
				'No' => 'Incorrect:  It comes after the third of July.')),
		array('Question' => 'How many birthdays does the average person?',
			'Answers' => array(
				'I Don\'t Know' => 'Incorrect:  Everyone was born on just ' .
					'one day.',
				'1' => 'Correct.',
				'2' => 'Incorrect:  Everyone was born on just one day.',
				'3-4' => 'Incorrect:  Everyone was born on just one day.',
				'5-9' => 'Incorrect:  Everyone was born on just one day.',
				'10 or more' => 'Incorrect:  Everyone was born on just one ' .
					'day.')),
		array('Question' => 'Some months have 31 days; how many have 28?',
			'Answers' => array(
				'I Don\'t Know' => 'Incorrect:  All months have 28 days.',
				'1' => 'Incorrect:  All months have 28 days.',
				'2' => 'Incorrect:  All months have 28 days.',
				'3' => 'Incorrect:  All months have 28 days.',
				'4' => 'Incorrect:  All months have 28 days.',
				'6' => 'Incorrect:  All months have 28 days.',
				'9' => 'Incorrect:  All months have 28 days.',
				'12' => 'Correct.')),
		array('Question' => 'How many outs are there in an inning?',
			'Answers' => array(
				'I Don\'t Know' => 'Incorrect:  There are 6; 3 per side.',
				'2' => 'Incorrect:  There are 6; 3 per side.',
				'3' => 'Incorrect:  There are 6; 3 per side.',
				'6' => 'Correct',
				'8' => 'Incorrect:  There are 6; 3 per side.')),
		array('Question' => 'Is it legal for a man in California to marry ' .
			'his widow\'s sister?',
			'Answers' => array(
				'I Don\'t Know' => 'Incorrect:  No, because he is dead.',
				'Yes' => 'Incorrect:  No, because he is dead.',
				'No' => 'Correct')),
		array('Question' => 'Divide 30 by 1/2 and add 10.  What is the ' .
			'answer?',
			'Answers' => array(
				'I Don\'t Know' => 'Incorrect.  70:  30 divided by 1/2 ' .
					'is 60.',
				'10' => 'Incorrect:  70:  30 divided by 1/2 is 60.',
				'25' => 'Incorrect:  70:  30 divided by 1/2 is 60.',
				'35' => 'Incorrect:  70:  30 divided by 1/2 is 60.',
				'50' => 'Incorrect:  70:  30 divided by 1/2 is 60.',
				'70' => 'Correct.')),
		array('Question' => 'If there are 3 apples and you take away 2, how ' .
			'many apples do you have?',
			'Answers' => array(
				'I Don\'t Know' => 'Incorrect.  If you took 2, you have 2 ' .
					'apples.',
				'0' => 'Incorrect:  If you took 2, you have 2 apples.',
				'1' => 'Incorrect:  If you took 2, you have 2 apples.',
				'2' => 'Correct.',
				'3' => 'Incorrect:  If you took 2, you have 2 apples.',
				'4' => 'Incorrect:  If you took 2, you have 2 apples.')),
		array('Question' => 'A doctor gives you three pills, telling you to ' .
			'take one pill every half hour.  How many minutes would the ' .
			'pills last?',
			'Answers' => array(
				'I Don\'t Know' => 'Incorrect:  60 minutes.  Start with the ' .
					'first pill.  30 minutes later you take the second.  ' .
					'Another 30 minutes later and you would take the third.',
				'20' => 'Incorrect:  60 minutes.  Start with the first pill.  ' .
					'30 minutes later you take the second.  Another 30 ' .
					'minutes later and you would take the third.',
				'30' => 'Incorrect:  60 minutes.  Start with the first pill.  ' .
					'30 minutes later you take the second.  Another 30 ' .
					'minutes later and you would take the third.',
				'40' => 'Incorrect:  60 minutes.  Start with the first pill.  ' .
					'30 minutes later you take the second.  Another 30 ' .
					'minutes later and you would take the third.',
				'60' => 'Correct.',
				'90' => 'Incorrect:  60 minutes.  Start with the first pill.  ' .
					'30 minutes later you take the second.  Another 30 ' .
					'minutes later and you would take the third.')),
		array('Question' => 'A farmer has 17 sheep, and all but 9 die.  ' .
			'How many are left?',
			'Answers' => array(
				'I Don\'t Know' => 'Incorrect:  9 are left.',
				'1' => 'Incorrect:  9 are left.',
				'3' => 'Incorrect:  9 are left.',
				'5' => 'Incorrect:  9 are left.',
				'7' => 'Incorrect:  9 are left.',
				'9' => 'Correct.')),
		array('Question' => 'How many animals of each gender did Moses take ' .
			'on the ark?',
			'Answers' => array(
				'I Don\'t Know' => 'Incorrect:  Moses didn\'t have an ark, ' .
					'Noah did.',
				'0' => 'Correct.',
				'1' => 'Incorrect:  Moses didn\'t have an ark, Noah did.',
				'2' => 'Incorrect:  Moses didn\'t have an ark, Noah did.',
				'3' => 'Incorrect:  Moses didn\'t have an ark, Noah did.')),
		array('Question' => 'How many two cent stamps are there in a dozen?',
			'Answers' => array(
				'I Don\'t Know' => 'Incorrect:  There are 12 of anything in ' .
					'a dozen.',
				'1' => 'Incorrect:  There are 12 of anything in a dozen.',
				'3' => 'Incorrect:  There are 12 of anything in a dozen.',
				'6' => 'Incorrect:  There are 12 of anything in a dozen.',
				'9' => 'Incorrect:  There are 12 of anything in a dozen.',
				'12' => 'Correct.'))));
				