<?PHP

$GLOBALS['Tests']['Love'] = array(
   'Version' => '1.0',
   'Summary' => 'This is designed to view your opinions about marrige and ' .
      'how you would treat your significant other.',
   'Data' => array(
      array('Question' => 
            "You are walking to your boyfriend's or girlfriend's house.
      	     There are two roads to get there.  One is a straight path to
	     take you there quickly, but is very plain and boring.  The
	     other is significantly longer, but is full of wonderful
	     sights and interesting things.  Which one do you take to get
	     to your significant other's house, short or long?",
	    'AnswerDesc' => 'The road represents your attitude towards ' .
	                    'love.  In this first question, where you are ' .
			    'walking towards your love\'s house, it ' .
			    'specifically deals with falling in love.',
	    'Answers' => array(
	       'Short' => 'The short road represents that you fall in love ' .
	                  'quickly and easily.',
	       'Long' => 'The long road signifies that you take your time ' .
	                 'to fall in love and do not fall in love as ' .
			 'easily')),
      array('Question' =>
	    "On the way, you see two rose bushes.  One is full of red roses,
	     the other is full of white.  You decide to pick 20 roses for
	     your sweetie, of any color combination.  What number of white
	     and red roses do you pick?",
	    'AnswerDesc' => 'The number of red roses represents how much ' .
	                    'you give in a relationship, while the number ' .
			    'of white represents what you expect in return.',
	    'Answers' => array(
	       '20 red, 0 white' => 'You will give about 100% and expect ' .
	       	   	  	    '0% in return.',
	       '19 red, 1 white' => 'You will give about 95% and expect ' .
	       	   	  	    '5% in return.',
	       '18 red, 2 white' => 'You will give about 90% and expect ' .
	       	   	  	    '10% in return.',
	       '17 red, 3 white' => 'You will give about 85% and expect ' .
	       	   	  	    '15% in return.',
	       '16 red, 4 white' => 'You will give about 80% and expect ' .
	       	   	  	    '20% in return.',
	       '15 red, 5 white' => 'You will give about 75% and expect ' .
	       	   	  	    '25% in return.',
	       '14 red, 6 white' => 'You will give about 70% and expect ' .
	       	   	  	    '30% in return.',
	       '13 red, 7 white' => 'You will give about 65% and expect ' .
	       	   	  	    '35% in return.',
	       '12 red, 8 white' => 'You will give about 60% and expect ' .
	       	   	  	    '40% in return.',
	       '11 red, 9 white' => 'You will give about 55% and expect ' .
	       	   	  	    '45% in return.',
	       '10 red, 10 white' => 'You will give about 50% and expect ' .
	       	   	  	    '50% in return.',
	       '9 red, 11 white' => 'You will give about 45% and expect ' .
	       	   	  	    '55% in return.',
	       '8 red, 12 white' => 'You will give about 40% and expect ' .
	       	   	  	    '60% in return.',
	       '7 red, 13 white' => 'You will give about 35% and expect ' .
	       	   	  	    '65% in return.',
	       '6 red, 14 white' => 'You will give about 30% and expect ' .
	       	   	  	    '70% in return.',
	       '5 red, 15 white' => 'You will give about 25% and expect ' .
	       	   	  	    '75% in return.',
	       '4 red, 16 white' => 'You will give about 20% and expect ' .
	       	   	  	    '80% in return.',
	       '3 red, 17 white' => 'You will give about 15% and expect ' .
	       	   	  	    '85% in return.',
	       '2 red, 18 white' => 'You will give about 10% and expect ' .
	       	   	  	    '90% in return.',
	       '1 red, 19 white' => 'You will give about 5% and expect ' .
	       	   	  	    '95% in return.',
	       '0 red, 20 white' => 'You will give about 0% and expect ' .
	       	   	  	    '100% in return.')),
      array('Question' => 
	    "You finally get to your boyfriend's or girlfriend's house.
	     A family member answers the door.  You can have them go get
	     your boyfriend/girlfriend or you can go yourself.  Which
	     do you do?",
	    'AnswerDesc' => 'This question represents your attitude ' .
	    		    'towards handling relationship problems.',
	    'Answers' => array(
	       'Go yourself' => 'You are a more direct person and like ' .
	                        'to work problems out immediately.',
	       'Send a family member' => 'You like to avoid problems and ' .
	       	       	      	      	 'hope they will solve themselves.')),
      array('Question' =>
	    "You go up to your girlfriend's or boyfriend's room, but nobody
	     is there.  You decide to leave the roses.  Do you leave them
	     by the windowsill or on the bed?",
	    'AnswerDesc' => 'The placement of roses determines how much ' .
	                    'like to see your boyfriend or girlfriend.',
	    'Answers' => array(
	       'Windowsill' => 'You are alright with not seeing him or ' .
	        	       'her as much.',
	       'Bed' => 'You like to see him or her a lot.')),
      array('Question' =>
	    "Later, it's time for bed.  You and your boyfriend/girlfriend
	     go to sleep in separate rooms.  In the morning, when it is time
	     for both of you to get up, you go into his or her room and
	     check up on them.  When you arrive, is he or she awake or 
	     asleep?",
	    'AnswerDesc' => 'This question reflects your attitude on their ' .
	                    'personality.',
	    'Answers' => array(
	       'Awake' => 'You expect him or her to change for you.',
	       'Asleep' => 'You love your boyfriend or girlfriend the way ' .
	                   'they are.')),
      array('Question' =>
      	    "Now it is time for you to go back home.  Do you take the short,
	     plain road or the longer, more interesting road?",
	    'AnswerDesc' => 'This last question is symbolic for the length ' .
	                    'of your relationships.',
	    'Answers' => array(
	       'Short' => 'You tend to fall out of love easily.',
	       'Long' => 'You will tend to stay in love for a long time.'))));
