<?php

$GLOBALS['Tests']['Priorities'] = array(
	'Version' => '1.0',
	'Summary' => 'What ranks as the most important in your life?  ' . 'What\'s next?',
	'Data' => array(
		'All of these things are happening at once.  Please rank them in
      importance in your life.  Do not try to plan things such as "If I
      answer the door, the person can turn off the water in the kitchen."',
		'Your baby is crying and needs you.',
		'The telephone is ringing, you are expecting an important phone call,
      and you have no answering machine or voicemail available.',
		'The doorbell is sounding and you hear the person knocking on the
      door.',
		'There is dry laundry on the line outside and it is beginning to rain.',
		'The water faucet in the kitchen is running.',
		array(
			'Question' => 'What is the most important thing in your life at this moment?',
			'AnswerDesc' => 'The most important event is ...',
			'Answers' => array(
				'Attend to Baby' => 'The baby represents your family.',
				'Answer Telephone' => 'The telephone represents your job.',
				'Answer Door' => 'The person at the door represents your friends.',
				'Take in the Laundry' => 'The laundry represents your sex life.',
				'Turn off the Water' => 'The running water represents your money or wealth.'
			)
		),
		array(
			'Question' => 'What comes second?',
			'AnswerDesc' => 'The second most important event is ...',
			'Answers' => array(
				'Attend to Baby' => 'The baby represents your family.',
				'Answer Telephone' => 'The telephone represents your job.',
				'Answer Door' => 'The person at the door represents your friends.',
				'Take in the Laundry' => 'The laundry represents your sex life.',
				'Turn off the Water' => 'The running water represents your money or wealth.'
			)
		),
		array(
			'Question' => 'What comes third?',
			'AnswerDesc' => 'The event that ranks about average is ...',
			'Answers' => array(
				'Attend to Baby' => 'The baby represents your family.',
				'Answer Telephone' => 'The telephone represents your job.',
				'Answer Door' => 'The person at the door represents your friends.',
				'Take in the Laundry' => 'The laundry represents your sex life.',
				'Turn off the Water' => 'The running water represents your money or wealth.'
			)
		),
		array(
			'Question' => 'What comes fourth?',
			'AnswerDesc' => 'The second least important thing in your life ' . 'is ...',
			'Answers' => array(
				'Attend to Baby' => 'The baby represents your family.',
				'Answer Telephone' => 'The telephone represents your job.',
				'Answer Door' => 'The person at the door represents your friends.',
				'Take in the Laundry' => 'The laundry represents your sex life.',
				'Turn off the Water' => 'The running water represents your money or wealth.'
			)
		),
		array(
			'Question' => 'What comes fifth?',
			'AnswerDesc' => 'The least important event is ...',
			'Answers' => array(
				'Attend to Baby' => 'The baby represents your family.',
				'Answer Telephone' => 'The telephone represents your job.',
				'Answer Door' => 'The person at the door represents your friends.',
				'Take in the Laundry' => 'The laundry represents your sex life.',
				'Turn off the Water' => 'The running water represents your money or wealth.'
			)
		)
	)
);
