<?PHP

$GLOBALS['Tests']['World Leader'] = array(
   'Version' => '1.0',
   'Summary' => 'Who would you want as the world leader?',
   'Data' => array(
      "It is time to elect a world leader, and your vote counts!  Here's
      the facts about the three leading candidates.",
      "Candidate A:  Associates with crooked politicians and consults with
      astrologists.  He's had two mistresses.  He also chain smokes and
      drinks 8 to 10 martinis a day.",
      "Candidate B:  He was kicked out of office twice, sleeps until noon,
      used opium in college, and drinks a quart of whiskey every evening.",
      "Candidate C:  He is a decorated war hero.  He's a vegetarian, doesn't
      smoke, drinks an occasional beer, and hasn't had any extra-marital
      affairs.",
      array('Question' =>
      	    "Which candidate do you like the most?",
	    'Answers' => array(
	       'Candidate A' =>
	          'Your candidate was Franklin D. Roosevelt (FDR).',
	       'Candidate B' =>
	          'You picked Winston Churchill.',
	       'Candidate C' =>
	          'This person is Adolph Hitler.'))));
