<?php
/* Sprint File Uploader
 * 
 * Copyright (C) 2009 - Tyler Akins
 * Licensed under the GNU GPL software license.
 * See the LEGAL file for legal information
 * See http://rumkin.com/tools/sprint/ for more information about these tools
 */

?>

<p>I have had one report that they received a Data Error 903 message when their ringer was too big.  Try making the file smaller by changing the format or cutting it down to 30 seconds.</p>
