<?PHP

include 'county_bounds.php';

$fp = fopen('bounds.php', 'w');
fputs($fp, "<?PHP\n// Automatically generated by build_county_boundaries.php\n");
fputs($fp, "// Simplified by build_state_boundaries.php\n");

$GLOBALS['StateBounds'] = array();
foreach ($GLOBALS['CountyBounds'] as $c => $b)
{
    $s = substr($c, 0, 2);
    if (! isset($GLOBALS['StateBounds'][$s]))
    {
	$GLOBALS['StateBounds'][$s] = array($b[0], $b[1], array($c));
    }
    else
    {
	$s = &$GLOBALS['StateBounds'][$s];
	$s[0][0] = min($s[0][0], $b[0][0]);
	$s[0][1] = max($s[0][1], $b[0][1]);
	$s[1][0] = min($s[1][0], $b[1][0]);
	$s[1][1] = max($s[1][1], $b[1][1]);
	$s[2][] = $c;
	unset($s);
    }
}


// Write my own
fputs($fp, '$GLOBALS[\'StateBounds\'] = array(');
$comma = 0;
foreach ($GLOBALS['StateBounds'] as $k => $v)
{
    if ($comma)
      fputs($fp, ',');
    $comma = 1;
    fputs($fp, "\n  '$k'=>array(array(" . $v[0][0] . ',' . $v[0][1] . '),');
    fputs($fp, 'array(' . $v[1][0] . ',' . $v[1][1] . '),array(');
    $comma2 = 0;
    foreach ($v[2] as $vv)
    {
	if ($comma2)
	  fputs($fp, ',');
	$comma2 = 1;
	fputs($fp, '\'' . $vv . '\'');
    }
    fputs($fp, '))');
}
fputs($fp, ");\n\n");

fputs($fp, '$GLOBALS[\'CountyBounds\'] = array(');
$comma = 0;
foreach ($GLOBALS['CountyBounds'] as $k => $v)
{
    if ($comma)
      fputs($fp, ',');
    $comma = 1;
    fputs($fp, "\n  '$k'=>array(array(" . $v[0][0] . ',' . $v[0][1] .
	  '),array(' . $v[1][0] . ',' . $v[1][1] . '))');
}
fputs($fp, ");\n\n");
