<?PHP

include('../../functions.inc');

StandardHeader(array('title' => 'Geographic Navigation',
	'topic' => 'web',
	'callback' => 'include_js'));

?>
	<div style="background-color: black; width: 350px; float: right">
		<div style="text-align: center; padding: 15px">
			<IMG SRC="media/geonav/na.jpg" NAME="World" WIDTH="320"	ONLOAD="setTimeout('UpdateMap()', 1)" HEIGHT="320">
		</div>
		<div style="width: 200px; float: left">
			<IMG SRC="media/geonav/globe.gif" WIDTH="200" HEIGHT="81" USEMAP="#map1" BORDER="0">
			<MAP NAME="map1">
				<AREA SHAPE="POLY" COORDS="174,35,163,44,151,46,162,72,196,76,198,47" HREF="javascript:GoTo(4)">
				<AREA SHAPE="POLY" COORDS="126,0,141,45,163,40,183,18,196,15,196,2"	HREF="javascript:GoTo(3)">
				<AREA SHAPE="POLY" COORDS="136,35,124,4,105,3,93,13,87,30,93,47,103,53,110,74,124,67,136,53" HREF="javascript:GoTo(2)">
				<AREA SHAPE="POLY" COORDS="67,38,48,44,53,78,70,79,88,50,77,39" HREF="javascript:GoTo(1)">
				<AREA SHAPE="POLY" COORDS="92,1,88,12,65,34,45,44,23,24,4,19,1,1,92,1" HREF="javascript:GoTo(0)"> 
			</MAP>
		</div>
		<div style="width: 130px; float: right; text-align: center; font-size: 0.7em; font-weight: bold">
			<a href="javascript:GoTo(0)" style="color: yellow; text-decoration: none">North America</a><br>
			<a href="javascript:GoTo(1)" style="color: yellow; text-decoration: none">South America</a><br>
			<a href="javascript:GoTo(2)" style="color: yellow; text-decoration: none">Africa &amp; Europe</a><br>
			<a href="javascript:GoTo(3)" style="color: yellow; text-decoration: none">Asia and Russia</a><br>
			<a href="javascript:GoTo(4)" style="color: yellow; text-decoration: none">Australia</a><br>
			<a href="javascript:SpinGlobe()" style="color: yellow; text-decoration: none">-- Spin Globe --</a>
		</div>
		<div style="clear: both">
		</div>
	</div>
	<div id="geo_info_loading" style="display: none">
		<h1 align=center>Loading ...</h1>
		<p>Please wait for the world to revolve once so the world gets loaded.</p>
	</div>
	<div id="geo_info_na" style="display: none">
		<h1 align=center>North America</h1>
		<h2>Navigation</h2>
		<p>Just click on the globe to the left or the stretched out globe in the
		lower left.  The globe will rotate and this frame will refresh.</p>
		<h2>Download</h2>
		<p>If you use this code, I'd appreciate credit in your JavaScript.
		You can either save this page and all of the images that it uses, or I
		have a <a href="geonav.zip">slightly older version</a> as a zip file.</p>
		<p><a href="#" onclick="LoadNav('credits'); return false">Credits</a></p>
	</div>
	<div id="geo_info_sa" style="display: none">
		<h1 align=center>South America</h1>
		<p>Insert links for South America here</p>
		<p>If you get creative, you can use this type of thing to showcase links
		about a single city, country, or other geographic region.</p>
	</div>
	<div id="geo_info_af" style="display: none">
		<h1 align=center>Africa and Europe</h1>
		<p>Insert links relative to these areas here.</p>
		<p>If you get extremely creative, you could write a program that does a
		bubble-zoom effect on a network of nodes, and use the images that were
		created in here instead of using pictures of a globe.</p>
	</div>
	<div id="geo_info_as" style="display: none">
		<h1 align=center>Asia</h1>
		<p>Insert links relative to Asia here.</p>
		<p>I tried using higher quality pictures, but they slowed down the browser
		too much.  I also tried having a path from where you were directly to where
		you were going, but that was a huge amount of images.</p>
	</div>
	<div id="geo_info_au" style="display: none">
		<h1 align=center>Australia</h1>
		<p>Insert links relative to Australia here.</p>
		<p>For added flashiness, you could rewrite this type of idea in Flash.  I
		bet it would be easier if you could make a sphere, put a globe texture on
		it, and then just spin the ball wherever you like.  Zooming, bouncing, and
		some warping effects would make the globe seem nicely animated.</p>
	</div>
	<div id="geo_info_credits" style="display: none">
		<h1 align=center>Credits</h1>
		<UL>
		<LI>Images are generated by the <A
		HREF="http://www.fourmilab.ch/earthview/">Earth Viewer</A> by
		<A HREF="http://www.fourmilab.ch/">John Walker</A></LI>
		<LI>Satellite data that Earth Viewer uses is from
		<A HREF="http://livingearth.com/">The Living Earth</A></LI>
		<LI>Positioning on the globe was done with a shareware Windows program,
		<A HREF="http://www.amiglobe.com/">Amiglobe 99</A> </LI>
	</div>
<?PHP

StandardFooter();


function include_js() {
?>
<script language="JavaScript"><!--
// Set up the Transfer Image arrays
var TransferImages = new Array(47);
var Filled = 0;
var KeyImageNumber = new Array(5);

// Set up the country names
var CountryNames = new Array(5);
CountryNames[0] = "na"; // North America
CountryNames[1] = "sa"; // South America (and maybe Antartica?)
CountryNames[2] = "af"; // Africa and Europe
CountryNames[3] = "as"; // Asia
CountryNames[4] = "au"; // Australia

// Set up individual motions
// Usage:  SetUpImages(Continent_From, Continent_To, Maximum_Number_of_Image)
SetUpImages(0, 1, 6);   // North America to South America
SetUpImages(1, 2, 10);  // South America to Africa & Europe
SetUpImages(2, 3, 9);   // Africa & Europe to Asia
SetUpImages(3, 4, 5);   // Asia to Australia
SetUpImages(4, 0, 17);  // Australia to North America

// Sets up the transfer images to make the world spin
function SetUpImages(From, To, Number) {
	KeyImageNumber[From] = Filled;

	TransferImages[Filled] = new Image();
	TransferImages[Filled].src = "media/geonav/" + CountryNames[From] + ".jpg";

	Filled ++;

	var PathBase = "media/geonav/" + CountryNames[From] + "-" + CountryNames[To] + "-";
	for (var i = 1; i < Number; i ++) {
		// Skip the first one since it's the same as the ??.jpg files
		var Path = PathBase;
		if (i < 100) {
			Path += "0";
			if (i < 10) {
				Path += "0";
			}
		}
		TransferImages[Filled] = new Image();
		TransferImages[Filled].src = Path + i + ".jpg";

		Filled ++;
	}
}

var CurrentLocation = 0;
var Step = 1;
var Timeout = 0;
var Movement = 0;

function SpinGlobe() {
	Movement += Filled;
	if (Movement == Filled) {
		UpdateMap();
	}
}

function GoTo(Target) {
	Target = KeyImageNumber[Target];

	if (Target == CurrentLocation) {
		return;
	}
	if (Target < CurrentLocation) {
		Target += Filled;
	}
	var Diff1 = Target - CurrentLocation;
	Target -= Filled;
	var Diff2 = CurrentLocation - Target;
	if (Diff2 < Diff1) {
		Step = -1;
		Movement = Diff2;
	} else {
		Step = 1;
		Movement = Diff1;
	}

	LoadNav("");

	UpdateMap();
}

function UpdateMap() {
	if (Movement > 0) {
		clearTimeout(Timeout);
		CurrentLocation += Step;
		Movement --;

		if (CurrentLocation >= Filled) {
			CurrentLocation -= Filled;
		}
		if (CurrentLocation < 0) {
			CurrentLocation += Filled;
		}

		document.World.src = TransferImages[CurrentLocation].src;
	} else if (Movement == 0) {
		Timeout = setTimeout("GoGoGadgetMenu()", 100);
	}
}

function GoGoGadgetMenu() {
	for (var i = 0; i < 5; i ++) {
		if (CurrentLocation == KeyImageNumber[i]) {
			LoadNav(CountryNames[i]);
		}
	}
}

function LoadNav(divId) {
	ShowHideDiv('loading', 0);
	ShowHideDiv('na', 0);
	ShowHideDiv('sa', 0);
	ShowHideDiv('af', 0);
	ShowHideDiv('as', 0);
	ShowHideDiv('au', 0);
	ShowHideDiv('credits', 0);
	ShowHideDiv(divId, 1);
}

function ShowHideDiv(id, show) {
	var d = document.getElementById('geo_info_' + id);
	if (d) {
		if (show) {
			d.style.display = "block";
		} else {
			d.style.display = "none";
		}
	}
}

function GlobeOnload() {
	LoadNav('loading');
	window.setTimeout('SpinGlobe()', 10);
	if (GlobeOldOnload) {
		GlobeOldOnload();
	}
}

GlobeOldOnload = window.onload;
window.onload = GlobeOnload;
// --></script>
<?PHP
}
