/* Do not edit this file directly!            */
/* This is generated by 'util/gen_version.sh' */
/* Edit marco.rcp instead.                    */
#define APP_VERSION "3.1"
#define MARCO_MAJOR_VERSION 3
#define MARCO_MINOR_VERSION 1
#define COMPILE_DATE "March 14, 2005 at 18:17"
