<p>In various editions of the <i>Wall Journal</i>, Frank Hodgson explored an
ancient Mayan wall.  What is unique about the wall is that when sound hits
it, the pitch of the sound is raised before being reflected back.  It is
possible to use this technology to make sound absorbing walls for highways
and inside the cities.</p>

<p>The issues that have some bearing on the alteration of sound by the wall
are:</p>

<ul>
<li>Issue 11, Jan-Feb 1994, p. 18-19
<li>Issue 13, May-Jun 1994, p. 8-9, 13
<li>Issue 15, Sep-Oct 1994, p. 14-15
<li>Issue 19, Sep-Oct 1995, p. 6-7, 22-23
<li>Issue 31, Sep-Oct 1997, p. 8-9
</ul>

<p>People who are interested in this are asked to call 415-493-5511 or
write to:

<blockquote>Frank Hodgson<br>
The Kilo Foundation, Inc.<br>
708 Matadero Ave.<br>
Palo Alto, CA  94036</blockquote>

<p>Backissues of the <i>Wall Journal</i> are available from their web site
(for a limited time; the magazine is discontinued) at <a
href="http://www.thewalljournal.com/">http://www.thewalljournal.com</a>.</p>