var fortunes = [
	"Accept something that you cannot change, and you will feel better.",
	"Accept the next job offer you get.",
	"A chance meeting opens new doors to success and friendship.",
	"A close friend will help you find a hidden talent.",
	"A confidential tip will clue you in to a great financial deal.",
	"Actions speak louder than words.",
	"A cynic is a person who looks down at those above.",
	"Advice given to you will be well worth following.",
	"A financial investment will yield returns beyond your wildest hopes.",
	"A financial venture may turn a profit sooner than expected.",
	"A good time to start something new.",
	"A great man never ignores the simplicity of a child.",
	"A liar is not believed even when telling the truth.",
	"A love relationship takes on added dimension.",
	"Always begin with an end in mind.",
	"Always remember where you are going and never forget where you've been.",
	"A member of your family will soon make you proud.",
	"A modest man never talks to himself.",
	"An admirer is concealing his affection for you.",
	"An admirer is too shy to greet you.",
	"A need is really a strong want.",
	"An emptiness will soon be filled.",
	"An outstanding opportunity will soon present itself to you.",
	"Answers that sound good aren't necessarily good sound answers.",
	"Answers that sound good aren't necessarily good sound answers.",
	"An unexpected visitor will bring you good blessings.",
	"A peaceful mind generates power.",
	"A pleasant journey to places far away.",
	"A pleasant journey to places far away.",
	"A pleasant journey to places far away.",
	"A quiet evening with friends is the best tonic for a long day.",
	"Arriving at one goal is the starting point to another.",
	"A smile is the shortest distance between two people.",
	"As the wallet grows, so do the needs.",
	"A sweet surprise awaits you.",
	"At 20 years of age the will reigns, at 30 the wit, at 40 the judgment.",
	"A thrilling time is in your immediate future.",
	"A tidy sum is coming your way.",
	"Attention is the mother of memory.",
	"avoid agreeing with people merely to keep peace.",
	"Avoid focusing on the negative aspects of the past.",
	"Avoid misunderstanding by keeping your ears open.",
	"Avoid remembering negative aspects of the past.",
	"A wish will be granted after a long delay.",
	"A wish will be granted after a long delay.",
	"Be alert, practical and honest.",
	"Be careful and systematic in your business arrangements.",
	"Be considerate of your teachers.",
	"Be flexible! Opportunities for success are all around you.",
	"Be generous, and the favor will be returned.",
	"Begin nothing until you have considered how it is to be finished.",
	"Being with loved ones is the basis for real security.",
	"Being yourself is always the best fashion.",
	"Be merry and wise.",
	"Be prepared to modify your plan.",
	"Be prepared to receive something special.",
	"Be smart, but never show it.",
	"Better signs are approaching.",
	"Be willing to be uncomfortable. Be comfortable being uncomfortable. It may get tough.",
	"Be yourself and you will always be in fashion.",
	"Big words often hide small ideas.",
	"Build bridges not walls.",
	"Business trips bring excellent results, especially for sales.",
	"By the work one knows the worker.",
	"Change your thoughts and you change the world.",
	"Cleaning up the past will always clear up the future!",
	"Conceptualize. Organize. Sell. Then Do.",
	"Consolidate your interest while the lights are active.",
	"Courage is not simply one of the virtues, but the form of every virtue at the testing point.",
	"Demonstrate refinement in everything you do.",
	"Disasters can become blessings. Blessings can become disasters.",
	"Dispel negativity through creative activities.",
	"Do not burden yourself with trivial matters.",
	"Don't let unexpected situations throw you.",
	"Don't pursue happiness - create it.",
	"Don't put all your eggs in one basket.",
	"Don't slam the door you may want to pass back through.",
	"Don't worry about the world coming to an end. It's already tomorrow in Australia.",
	"Doubt is the beginning, not the end, of wisdom.",
	"Do unto others as you would have them do unto you.",
	"Dreams and reality do not always mix.",
	"Education and intelligence aren't the same thing!",
	"Enjoy the lighter things in life and deeper joys will follow.",
	"Even the smallest candle burns brighter in the dark.",
	"Everyone agrees you are the best.",
	"Everyone has ambitions.",
	"Everyone is interested in people who are interested in them.",
	"Excitement and intrigue follow you closely wherever you go!",
	"Explore an unpaved road with a new friend.",
	"Explore your own world by working together with your friends.",
	"Fame and fortune are coming your way.",
	"Fear is just excitement in need of an attitude adjustment.",
	"Fear is the root of all evil.",
	"Fight for it. You will come out on the top.",
	"Find release from your cares. Have a good time.",
	"For a good cause, wrongdoing may be virtuous.",
	"Forget yesterday: Tomorrow will be a golden day for you.",
	"Friends long absent are coming back to you.",
	"From the garden of your dreams many things can grow.",
	"Generosity and perfection are everlasting goals.",
	"Generosity and perfection are your assets and they show.",
	"Genius is more work than genius.",
	"Get ready for a daring adventure.",
	"Give yourself some peace and quiet for at least a few hours.",
	"God gave man limited ability, but unlimited ambition and desire.",
	"Good fortune in love as well as a better position.",
	"Good fortune in love as well as a better position.",
	"Good health will be yours for a long time.",
	"Good people are good because they've come to wisdom through failure.",
	"Goods that are not shared are not goods.",
	"Good things are being said about you.",
	"Good things are coming to you in due course of time.",
	"Good things come in invisible packages. You will be delighted.",
	"Good things will come to you in due time.",
	"Go to the elders when you feel a confidence crisis.",
	"Happier days are just ahead.",
	"Happiness is a state of mind.",
	"Happiness is a state of mind.",
	"Happiness is coming from an unexpected source.",
	"Happiness is in your future.",
	"Happy events will soon take place in your home.",
	"Happy news is on its way to you.",
	"Hardly anyone knows how much is gained by ignoring the future.",
	"Haste makes waste.",
	"Health and happiness are in your destiny.",
	"He who knows the most says the least.",
	"Hold yourself well in control; you will hear comforting news.",
	"Hold yourself well in control; you will hear comforting news.",
	"Honor is your greatest reward.",
	"Hope is the most precious treasure to a person.",
	"How dark is dark? How wise is wise?",
	"If it is meant to be, who are you to change that? It's time to believe it.",
	"If the idea you had three days ago still looks good, do it!",
	"If there are only 3 colors, 10 digits, and 7 notes; it's what we do with them that's important.",
	"If you carry your childhood with you, you never become older.",
	"If you feel you are right, stand firmly by your convictions.",
	"If you keep silent, no one can misquote you.",
	"If you think you're too small to be effective, you have never been in bed with a mosquito.",
	"If you want to succeed in business, avoid \"business as usual.\"",
	"If you want to win anything – a race, your self, your life – you have to go a little berserk.",
	"In charity, as the purse is emptied, the heart is filled.",
	"Inch-by-inch, life's a cinch. Yard-by-yard, it's very hard.",
	"Including others in your life will bring you great happiness.",
	"Investigate new possibilities with friends. Now is the time!",
	"In words of love a little exaggeration is ok.",
	"It doesn't matter. Who is without a flaw?",
	"It is better to have a hen tomorrow than an egg today.",
	"It is much easier to be critical than to create.",
	"It is proper to speak the truth.",
	"It is time to help a friend in need.",
	"It's tempting to make promises, but can you fulfill them all?",
	"It's time to treat yourself to something special.",
	"I was when I found out I could make mistakes that I knew I was on to something.",
	"Keep up the good work. You will be rewarded.",
	"Keep your ideas flexible, and don't ignore details.",
	"Kind words cost nothing.",
	"Learn how to refuse favors.",
	"Life is both complicated and very simple at the same time.",
	"Listen often to the quiet voice within.",
	"Look for the beauty in simplicity.",
	"Love is around the corner.",
	"Luck is coming your way.",
	"Many people will be drawn to you for your wisdom and insights.",
	"Measure how far you've come, not where you came from.",
	"Meekness is not weakness.",
	"Move forward.",
	"Never forget a friend, especially if he owes you.",
	"Never hesitate to tackle the most difficult problems.",
	"Never say never.",
	"No one ever went out of business because of low overhead.",
	"No one is happy who does not think himself so.",
	"Not every soil can bear all things.  Be practical.",
	"Nothing in the world is difficult if one sets his mind to it.",
	"Observe; listen; think; feel; use your intuition - then speak.",
	"One can never know the best that is in him.",
	"Only the mediocrea are always at their best.",
	"Others appreciate your expressive qualities.",
	"Others are impressed with your inner beauty.",
	"Others enjoy your radiance.",
	"Others recognize your sweet nature.",
	"Others will be impressed with your generosity.",
	"Others will take notice of your positive attitude.",
	"People say you have sharp sense and superb intellect.",
	"Persistence and determination alone are omnipotent.",
	"Pleasant surroundings and a happy time await you.",
	"Politeness costs nothing and gains everything.",
	"Practice is the best of all instructors.",
	"Progress is risky. You can't steal second and keep your foot on first.",
	"Pure pleasure is found in useful work.",
	"Rare experiences will enrich your life.",
	"Reality is for people who lack imagination.",
	"Romance comes to life this year in a very unusual sort of way.",
	"Second thoughts are often wiser than first impressions.",
	"Seek elegance rather than luxury, refinement instead of fashion.",
	"See the beauty in everything.",
	"Selflessness is the ultimate power.",
	"Sing and rejoice, fortune is smiling on you.",
	"Sitting towards the East may bring you good fortune.",
	"Socially, you will be involved with an enjoyable event.",
	"Someone is interested in you. Keep your eyes open.",
	"Someone special admires you.",
	"Someone with blue eyes admires you.",
	"Someone you care about seeks reconciliation.",
	"Some people never have anything except ideas. Go do it.",
	"Something wonderful is about to happen to you.",
	"Spring has sprung. Life is blooming.",
	"Step by step you will ascend the staircase to success.",
	"Stop searching forever – happiness is just next to you.",
	"Stop searching. Happiness will come to you.",
	"Stop waiting! Buy that ticket and take a trip today!",
	"Stop waiting! Buy that ticket. Take that special trip.",
	"Strike iron while it is hot.",
	"Success and happiness will come your way.",
	"Success and wealth are in your fate.",
	"Success comes with self-acceptance.",
	"Success is in starting a new project at work.",
	"Success will come with patience.",
	"Take care and sensitive you show towards others will return to you.",
	"That long-sought opportunity will soon arise.",
	"That special someone loves to see the light in your eyes.",
	"The best profit of future is the past.",
	"The cure for grief is motion.",
	"The expedient thing and the right thing are seldom the same thing.",
	"The eyes believe themselves, the ears believe other people.",
	"The face of nature reflects all of life's ups and downs.",
	"The fun side of a relationship begins to unfold.",
	"The harder the conflict, the more glorious the triumph.",
	"The heart has its reasons, which the reason does not know.",
	"The heart is a better judge than the intellect.",
	"The journey of a thousand miles begins with a single step.",
	"The joyfulness of a man prolongs his day.",
	"The measure of time to your next goal is the measure of your discipline.",
	"The memory of bad quality lasts longer than the shock of high prices.",
	"The mysterious side of your nature makes you most alluring.",
	"The really great man is the man who makes everyone feel great.",
	"There are many new opportunities that are being presented to you.",
	"There are many new opportunities that are being presented to you.",
	"There are no bad days; some are just better than others.",
	"There is nothing permanent except change.",
	"There is nothing that costs so little nor goes so far as courtesy.",
	"There is no time like the pleasant.",
	"There's a secret romance blooming! Go for it, in spite of your hesitation.",
	"There's nothing like good food, good wine, and a good mate.",
	"The surest way to have nothing to give is to give nothing.",
	"The time is right to reach your goals.",
	"They can because they think they can.",
	"They fail, and they alone, who have not striven.",
	"They that sow in tears shall reap in joy.",
	"This year will bring you much happiness.",
	"This year your highest priority will be your family.",
	"Those who laugh loud also cry hard.",
	"Those who laugh loud also cry hard.",
	"Time and patience are called for, many surprises await you!",
	"Time is the means that prevents everything from happening at once.",
	"To courageously shoulder the responsibility of one's mistake is character.",
	"Toil a while ... endure a while ... believe always ... and never turn back.",
	"Tomorrow is a good day for trying something new.",
	"Traveling more often is important for your health and happiness.",
	"Traveling this year will bring your life into greater perspective.",
	"True ideas possess greater ultimate power than physical might.",
	"Trust him, but still keep your eyes open.",
	"Try deviating from routine this weekend.",
	"Trying to outsmart everybody is the greatest folly.",
	"Understand yourself so you may understand others.",
	"Unnecessary possessions are unnecessary burdens.",
	"Use your natural versatility to keep from being bored.",
	"Versatility is one of your outstanding traits.",
	"Volunteering your time is true giving.",
	"Watch impulsiveness and a preference for something new just because it is different.",
	"Watch your relations with other people carefully, be reserved.",
	"We all smile in the same language.",
	"We all smile in the same language.",
	"Wealth and honor will come to you soon.",
	"Wealth is a means to an end ... not the end itself.",
	"Wealth is in your future.",
	"Wealth without wisdom is a fools' paradise",
	"We can learn from everyone, especially our enemies.",
	"Weigh your ideas carefully, they may make you rich.",
	"Welcome each day as a fresh new beginning.",
	"We rarely find that people have good sense unless they agree with us.",
	"What's more important – your goal, or others' opinions of your goal?",
	"What we acquire without sweat we give away without regret.",
	"What you see in the mirror, and what you are can be two different images.",
	"What you think is a problem is an opportunity for growth.",
	"When one door closes, another will open.",
	"When winter comes heaven will rain success on you.",
	"Whether you choose love or fame, you'll be able to handle either or both.",
	"Why simply live and let live? Live and help live.",
	"Wisdom is only found in truth.",
	"Woman's intuition is like feathers on an arrow – it may help the flight to truth.",
	"Worries will vanish if you tackle them bravely.",
	"You are always welcome in any gathering.",
	"You are both ingenious and methodical.",
	"You are broad minded and socially active.",
	"You are capable, competent, creative and careful.",
	"You are capable of seeing a philosophic meaning in the everyday events of life.",
	"you are careful and systematic.",
	"You are cheerful and well-liked.",
	"You are courteous, diplomatic, and affable and may find happiness in politics and public service.",
	"You are far more influential than you think.",
	"You are generous, affectionate and impulsive.",
	"You are good-natured, practical and firm in your point of view.",
	"You are imbued with extraordinary vitality.",
	"You are incredibly clever. Others often come to you for advice.",
	"You are kind and trustworthy. Others often count on you.",
	"You are kind-hearted and hospitable.",
	"You are naturally competitive.",
	"You are never bitter, deceptive or petty.",
	"You are next in line for promotion in your firm.",
	"You are one of the people who will go places in life.",
	"You are practical and down to earth.",
	"You are sociable and can get along with anyone.",
	"You are sociable and entertaining.",
	"You are strong and sensitive.",
	"You are strongly goal-directed.",
	"You are sympathetic to the problems of others.",
	"You are talented in many ways.",
	"You are the guiding star of his existence.",
	"You are the master of every situation.",
	"You are very persistent in pursuing your goals in life.",
	"You are very wealthy, but you don't know it.",
	"You are what you think about.",
	"You can combine practicality, charm, and perseverance with a creative touch.",
	"You can never really have something until you give it away.",
	"You cannot eat your cake and have it too.",
	"You can prosper in the field of computers.",
	"You can prosper in the field of medical research.",
	"You can readily adjust to a new environment.",
	"You can talk your way out of almost anything.",
	"You can't solve problems for those people who don't want their problem solved.",
	"You can undertake and complete anything.",
	"You can work both alone or with others.",
	"You change the world with each thought, word, and action.",
	"You communicate a sense of harmony to others.",
	"You enjoy giving gifts of yourself to others, you will be rewarded!",
	"You excel at technical work.",
	"You have a great appreciation for beautiful things.",
	"You have a loving heart: let it show.",
	"You have an ability to sense and know higher truth.",
	"You have an active mind and a keen imagination.",
	"You have an ambitious nature and will make a name for yourself.",
	"You have an excellent capacity for making people feel at home.",
	"You have an uncanny willingness and ability to help others.",
	"You have an unusually magnetic personality.",
	"You have a strong desire to maintain peace.",
	"You have at your command the wisdom of the ages. Read!",
	"You have a winning way. Keep it.",
	"You have excellent concentration and are inclined to think deeply.",
	"You have firmness, a clear sense of direction, and the drive to reach your goals.",
	"You have no problems in your home that you will not be able to solve.",
	"You have only begun to scratch the surface of your real potential.",
	"You have sound business sense.",
	"You have strong, personal ideas and convictions. Treasure them.",
	"You have the ability to be very persuasive.",
	"You have the ability to channel your energies into constructive activities.",
	"You have the ability to plan a practical course for yourself and follow through.",
	"You have the ability to touch lives.",
	"You have the attitude of a winner.",
	"You have the rare ability to recognize ability in others.",
	"You have the rare gift to encourage ability in others.",
	"You'll accomplish more if you start now.",
	"You'll accomplish more later if you take some time for yourself.",
	"You'll never know what you can do until you try.",
	"You love a good challenge.",
	"You may find your horizons suddenly broadened.",
	"You never hesitate to tackle the most difficult problems.",
	"You never hesitate to tackle the most difficult problems.",
	"Your air of confidence naturally draws others to you.",
	"Your best three doctors are faith, time and patience.",
	"Your confidence and assurance attracts others.",
	"Your courage will reap rewards for you.",
	"Your dearest wish will come true.",
	"You're doomed to a life with a green thumb and a Midas touch.",
	"Your energy is at a peak. Channel it into creative activities.",
	"Your enthusiasm inspires people.",
	"Your fastidious nature has much more fun this year!",
	"Your fortune is as sweet as a cookie.",
	"Your good listening skills will open many doors.",
	"Your hard work will soon pay off.",
	"Your hidden creative talents will soon be revealed.",
	"Your home is a pleasant place from which you draw happiness.",
	"Your joyfullness will prolong your days.",
	"Your kindness is surely to be repaid.",
	"Your message must focus on the receiver. Ignore yourself.",
	"Your mind is filled with new ideas. Make use of them.",
	"Your natural charm will attract someone special.",
	"Your original ideas will get you well-deserved recognition.",
	"Your plans will be rewarding.",
	"Your present plans are going to succeed.",
	"Your present plans are going to succeed.",
	"Your sense of humor can light up a dreary day.",
	"Your sparkling eyes give a healing light to those you meet.",
	"Your thoughts are highly regarded.",
	"Your wit is sharp and quick. Avoid using sarcasm on an unsuspecting victim.",
	"You shall seek out new adventures.",
	"You should pay for this dinner. Be generous.",
	"You simplify your life in many ways and find great rewards.",
	"You take an optimistic view of life.",
	"Youth is a gift of nature. Middle age is a work of art.",
	"You will always be surrounded by those who love you.",
	"You will always be surrounded by true friends.",
	"You will always have good luck in your personal affairs.",
	"You will always have good luck in your personal affairs.",
	"You will always have good luck in your personal affairs.",
	"You will always live in interesting times.",
	"You will attend an unusual party.",
	"You will be a winner.",
	"You will be called to fill a position of high honor and responsibility.",
	"You will become an accomplished writer.",
	"You will be coming into a fortune.",
	"You will be successful in a business of your own.",
	"You will be successful in business and married life.",
	"You will be traveling and coming into a fortune.",
	"You will be unusually successful in business.",
	"You will brighten someone's day.",
	"You will do better in real estate than in stocks.",
	"You will enjoy doing something different this coming weekend.",
	"You will get an offer that will be hard to turn down.",
	"You will have good luck in business affairs.",
	"You will have many friends when you need them.",
	"You will have many friends when you need them.",
	"You will have some wonderful new experiences.",
	"You will inherit a large sum of money.",
	"You will live a long, prosperous life.",
	"You will live a long time, long enough to open many, many fortune cookies.",
	"You will make a fortune with your friend.",
	"You will make a name for yourself.",
	"You will make many changes before settling satisfactorily.",
	"You will profit through experience.",
	"You will receive a surprising gift very soon.",
	"You will soon be honored by someone you respect.",
	"You will soon be honored by someone you respect.",
	"You will soon be involved in many gatherings, parties and communications.",
	"You will soon be more aware of your growing awareness.",
	"You will soon be reminded of a fond memory.",
	"You will soon discover how truly fortunate you really are.",
	"You will soon take a very pleasant and successful trip.",
	"You will spend many years in comfort and material wealth.",
	"You will spend old age in comfort and material wealth.",
	"You will spend your old age surrounded by comfort and wealth.",
	"You will travel to many exotic places.",
	"You will travel to many places.",
	"You won't be bored for long! New adventures are on their way.",
	"You would make a good lawyer."
];
