<?php

$fn = 'data/app_a03.txt';
$outfn = 'counties.php';
$fp = fopen($fn, 'rb');
$data = fread($fp, filesize($fn));
fclose($fp);
$data = str_replace("\r\n", "\n", $data);
$data = str_replace("\r", "\n", $data);
$data = explode("\n", $data);
array_shift($data);
array_shift($data);
array_shift($data);
array_shift($data);
$counties = array();
$state_codes = array();

while ($data[0]) {
	$line = array_shift($data);
	preg_match('/^(..)     (...)     (.+)     (..)$/', $line, $matches);
	
	if (! isset($state_codes[$matches[4]]))$state_codes[$matches[4]] = $matches[1] * 1;
	$counties[ ($matches[1] . $matches[2]) * 1] = $matches[3];
}

$fp = fopen($outfn, 'w');
fputs($fp, "<?PHP\n");
fputs($fp, "// Automatically generated by $GLOBALS[PHP_SELF]\n");
fputs($fp, "\n");
fputs($fp, '$GLOBALS[\'CountyNames\'] = ' . var_export($counties, 1) . ";\n");
fputs($fp, '$GLOBALS[\'StateAbbrToCode\'] = ' . var_export($state_codes, 1) . ";\n");
fclose($fp);
